-- =====================================================================================
-- 2026-09-09_1730  The drift card names BOTH times, instead of only saying they differ
--   ops.v_calendar_push_health  (detail text only)
-- =====================================================================================
-- WHY ---------------------------------------------------------------------------------
-- The card an operator sees for a `jobber_time_differs` visit reads, in full:
--     "Same day in both, but the times differ. Syncing from Jobber will use Jobber's time."
-- It never says WHAT time Jobber has, so deciding which side is right means opening Jobber in
-- another tab. The `jobber_date_differs` arm has always interpolated its `jobber_date`, so the
-- pattern already existed and was simply not applied to the other two arms.
--
-- `surfaced_visits` carries `jobber_start_at` on every entry (1,078 of 1,078 over the last 45 days),
-- so this costs nothing: the value is already in the row the view reads.
--
-- Live example, the card showing right now would go from the sentence above to:
--     "Same day in both, but the times differ: we have 8:00 AM, Jobber has 11:15 AM. Syncing from
--      Jobber will use Jobber's time."
--
-- 🛑 THE CAST STAYS BEHIND THE REGEX GATE, for the reason `2026-08-17_1500` gave when it added it:
--    a malformed `jobber_start_at` must never be able to RAISE inside a view the Visit Calendar
--    depends on. The gate is the same escape-free POSIX-class test that arm already uses for its
--    re-validation, and the ELSE branch keeps the original wording verbatim, so a bad value
--    degrades to today's sentence rather than blanking the card.
-- ⚠ `to_char(..., 'FMHH12:MI AM')`: FM strips the padding, so it reads "8:00 AM" and not "08:00 AM".
-- ⚠ `v.start_at` can be NULL on the all-day arm, hence the COALESCE on both. On the time arm it is
--    never NULL in practice (the classifier only emits `jobber_time_differs` when both sides are
--    timed) but the COALESCE costs nothing and a NULL would otherwise swallow the whole sentence,
--    since `||` with NULL yields NULL.
--
-- ⚠ ALSO CHANGED, on the all-day arm: "will clear the time" -> "will CLEAR the time", and it now
--    names the time being cleared. That arm is the one automatic adoption must never take (adopting
--    an all-day Jobber value wipes the office's time), so the destructive half of the sentence
--    should not be the quietest part of it.
--
-- WHAT IS NOT CHANGED -----------------------------------------------------------------
-- The bold headline "This visit didn't reach Jobber." is an unconditional literal in the Visit
-- Calendar bundle, not in this view, and it is FALSE on 100% of drift cards: the candidate set
-- INNER JOINs `entity_source_links`, so a visit can only drift if it IS in Jobber. That is an app
-- change and it is not in this migration.
-- The raw machine string (`jobber_time_differs`) is rendered to operators by the app reading
-- `reason`; also app-side. And `since` has carried the true episode onset since `2026-08-03_1900`
-- and the app has never selected it, so no card shows its age. All three are app-side.
--
-- BODY WAS COPIED, NOT RETYPED (Supabase CLAUDE.md). This file was generated by reading
-- `pg_get_viewdef('ops.v_calendar_push_health', true)` and replacing exactly two anchors, each
-- asserted to occur exactly once. Every other byte is the live definition.
--
-- AUDIT (rule 8): view only, no table changed.
-- REVERSIBLE: yes. Restore the two literal strings; both are quoted verbatim in this header.
-- =====================================================================================

begin;

CREATE OR REPLACE VIEW ops.v_calendar_push_health AS
SELECT v.id AS visit_id,
    c.client_code,
    c.name AS client_name,
    v.visit_date,
    v.source,
    'push_failed'::text AS issue,
    f.reason,
    f.detail,
    f.created_at AS since
   FROM visit_sync_flags f
     JOIN visits v ON v.id = f.visit_id
     JOIN clients c ON c.id = v.client_id
  WHERE f.resolved_at IS NULL AND v.deleted_at IS NULL
UNION ALL
 SELECT v.id AS visit_id,
    c.client_code,
    c.name AS client_name,
    v.visit_date,
    v.source,
    'not_in_jobber'::text AS issue,
    NULL::text AS reason,
    NULL::text AS detail,
    v.created_at AS since
   FROM visits v
     JOIN clients c ON c.id = v.client_id
  WHERE (v.source = ANY (ARRAY['visit-calendar'::text, 'supabase_cron'::text])) AND v.visit_status = 'scheduled'::text AND v.deleted_at IS NULL AND v.created_at < (now() - '00:15:00'::interval) AND fn_visit_in_jobber_scope(v.id) AND NOT (EXISTS ( SELECT 1
           FROM entity_source_links e
          WHERE e.entity_type = 'visit'::text AND e.source_system = 'jobber'::text AND e.entity_id = v.id))
UNION ALL
 SELECT v.id AS visit_id,
    c.client_code,
    c.name AS client_name,
    v.visit_date,
    v.source,
    'skip_removal_failed'::text AS issue,
    'skipped visit still linked to Jobber (removal did not complete)'::text AS reason,
    v.sync_state AS detail,
    v.updated_at AS since
   FROM visits v
     JOIN clients c ON c.id = v.client_id
  WHERE v.visit_status = 'skipped'::text AND v.deleted_at IS NULL AND (EXISTS ( SELECT 1
           FROM entity_source_links e
          WHERE e.entity_type = 'visit'::text AND e.source_system = 'jobber'::text AND e.entity_id = v.id))
UNION ALL
 SELECT v.id AS visit_id,
    c.client_code,
    c.name AS client_name,
    v.visit_date,
    v.source,
    'drift_surfaced'::text AS issue,
    sv.sv ->> 'reason'::text AS reason,
        CASE sv.sv ->> 'reason'::text
            WHEN 'jobber_date_differs'::text THEN ('Jobber has this visit on a different day ('::text || COALESCE(sv.sv ->> 'jobber_date'::text, '?'::text)) || ') than we do. Decide which is right - syncing from Jobber will move the visit.'::text
            WHEN 'jobber_all_day_vs_our_time'::text THEN (('Same day in both, but Jobber has no set time (all-day) while we have '::text || COALESCE(to_char(timezone('America/New_York'::text, v.start_at), 'FMHH12:MI AM'::text), 'one'::text)) || '. Syncing from Jobber will CLEAR the time.'::text)
            WHEN 'jobber_time_differs'::text THEN
            CASE
                WHEN (sv.sv ->> 'jobber_start_at'::text) ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T'::text THEN (((('Same day in both, but the times differ: we have '::text || COALESCE(to_char(timezone('America/New_York'::text, v.start_at), 'FMHH12:MI AM'::text), 'no time set'::text)) || ', Jobber has '::text) || to_char(timezone('America/New_York'::text, ((sv.sv ->> 'jobber_start_at'::text)::timestamp with time zone)), 'FMHH12:MI AM'::text)) || '. Syncing from Jobber will use Jobber''s time.'::text)
                ELSE 'Same day in both, but the times differ. Syncing from Jobber will use Jobber''s time.'::text
            END
            WHEN 'audit_read_fail'::text THEN 'We could not read this visit''s edit history, so the difference was not classified. It is re-checked every run.'::text
            ELSE 'Our schedule and Jobber''s disagree and the reconciler could not resolve it safely.'::text
        END AS detail,
    onset.first_seen AS since
   FROM ( SELECT sync_log.started_at,
            sync_log.details
           FROM sync_log
          WHERE sync_log.sync_source = 'jobber_visit_drift'::text AND sync_log.details ? 'surfaced_visits'::text
          ORDER BY sync_log.started_at DESC
         LIMIT 1) sl
     CROSS JOIN LATERAL jsonb_array_elements(sl.details -> 'surfaced_visits'::text) sv(sv)
     JOIN visits v ON v.id = ((sv.sv ->> 'id'::text)::bigint) AND v.deleted_at IS NULL AND v.visit_status = 'scheduled'::text
     JOIN clients c ON c.id = v.client_id
     LEFT JOIN LATERAL ( SELECT min(r.started_at) AS first_seen
           FROM sync_log r
          WHERE r.sync_source = 'jobber_visit_drift'::text AND r.details ? 'surfaced_visits'::text AND (EXISTS ( SELECT 1
                   FROM jsonb_array_elements(r.details -> 'surfaced_visits'::text) e(value)
                  WHERE ((e.value ->> 'id'::text)::bigint) = v.id)) AND r.started_at > COALESCE(( SELECT max(r2.started_at) AS max
                   FROM sync_log r2
                  WHERE r2.sync_source = 'jobber_visit_drift'::text AND r2.details ? 'surfaced_visits'::text AND NOT (EXISTS ( SELECT 1
                           FROM jsonb_array_elements(r2.details -> 'surfaced_visits'::text) e2(value)
                          WHERE ((e2.value ->> 'id'::text)::bigint) = v.id))), '-infinity'::timestamp with time zone)) onset ON true
  WHERE
        CASE sv.sv ->> 'reason'::text
            WHEN 'jobber_date_differs'::text THEN v.visit_date::text IS DISTINCT FROM (sv.sv ->> 'jobber_date'::text)
            WHEN 'jobber_all_day_vs_our_time'::text THEN v.start_at IS NOT NULL
            WHEN 'jobber_time_differs'::text THEN
            CASE
                WHEN (sv.sv ->> 'jobber_start_at'::text) ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T'::text THEN v.start_at IS DISTINCT FROM ((sv.sv ->> 'jobber_start_at'::text)::timestamp with time zone)
                ELSE true
            END
            ELSE true
        END;

commit;
