-- 2026-08-25_0400_lwt_state_and_punctuation_normalisation.sql
-- ---------------------------------------------------------------------------
-- Normalise what prints on the Miami-Dade LWT monthly form: the state abbreviation,
-- and typographic punctuation in client names.
--
-- Fred: "yes normalise both", after the endpoint status showed `state` arriving as
-- BOTH "FL" and "Florida", and typographic apostrophes in client names.
--
-- Measured before applying, and these are the numbers the VERIFY block asserts against:
--   690 rows / 589 in_scope / 126 tickets
--   state:  Florida 663 · FL 13 · null 14
--   curly apostrophe: 9 rows across 3 distinct names
--     Florida Food Eats LLC Fialkoff’s (Miami Beach) · (Surfside) · NOEL’S KIWI KITCHEN MIAMI BEACH
--   other non-ASCII in a NAME: 2 rows, 1 name -- "Fendi Château Residences"  <- MUST SURVIVE
--   non-ASCII in an ADDRESS:  10 rows -- "Española Way"                    <- MUST SURVIVE
--
-- 🛑 THE OBVIOUS IMPLEMENTATION OF THE FIRST WOULD FALSIFY A COMPLIANCE FORM.
--    `state = 'FL'` is the one-liner, and public.properties holds SIX values:
--        Florida 868 · FL 41 · California 5 · Quebec 2 · New York 1 · fl 1
--    Only Florida/FL/null reach this view TODAY, so a constant would look correct and
--    would silently relabel a Quebec or California property the first time one took a
--    Miami-Dade pickup. This maps explicitly, and anything unrecognised passes through
--    VERBATIM so it is visible rather than quietly wrong.
--
-- 🛑 THE SECOND IS NARROWER THAN IT SOUNDS: ACCENTED LETTERS ARE NOT NOISE, THEY ARE
--    THE CORRECT SPELLING. The non-ASCII here splits cleanly and only one half is an
--    artifact:
--        U+2019 curly apostrophe -> Fialkoff's, NOEL'S            ARTIFACT, normalised
--        U+00E2 in "Chateau", U+00F1 in "Espanola Way"            CORRECT, left alone
--    "Espanola Way" is a real Miami Beach street and "Fendi Chateau Residences" is the
--    business's registered name. Stripping those MISSPELLS a regulator-facing document,
--    which is worse than the inconsistency being fixed. So: punctuation only, and
--    `address` is deliberately NOT touched (its only non-ASCII is that n-tilde).
--
-- ⚠ PRESENTATION ONLY. `public.properties.state` and `public.clients.name` are
--   untouched, so every other app still shows what it always showed. Fixing it at
--   source would touch the Field Portal, the Client App and every work order, and is a
--   separate decision.
--
-- ⚠ Measured: `derm.v_lwt_monthly_rows` has ZERO dependent views and `rpa-derm-monthly`
--   selects `*`, so no caller needs editing. Column list unchanged, so CREATE OR
--   REPLACE works and no grant is lost.
--
-- ---------------------------------------------------------------------------
-- HOW THIS BODY WAS PRODUCED, because two separate transports corrupted it first and
-- both are worth knowing:
--
-- It was generated by substituting exactly two lines into live `pg_get_viewdef`
-- output (scratchpad genlwt.js), never retyped -- CREATE OR REPLACE takes the whole
-- body, so anything not reproduced is silently deleted.
--
-- 🛑 (1) `U&'\2019'` ARRIVED AS `U&'9'`. Unicode escapes get eaten in transit through
--     shell/JS string handling. `chr(8217)` is pure ASCII in the source and cannot be
--     damaged, so the substitution uses chr() throughout.
-- 🛑 (2) `String.prototype.replace` INTERPRETS `$&`, `` $` ``, `$'` AND `$1` IN THE
--     REPLACEMENT TEXT. The state branch contains the regex `'^[A-Za-z]{2}$'`, and
--     that `$'` means "everything after the match" -- it spliced the entire remainder
--     of the view back in, turning 31 lines into 68 with a duplicated FROM clause and
--     a truncated regex. **Use a function replacement, `.replace(a, () => b)`**, which
--     is taken literally. The tell was a line delta of +37 against a predicted +19;
--     without that prediction it would have applied and silently changed the view.
--
-- Audit (Rule 8): one view body. No table, column or grant on any audited table
-- changes.
--
-- @Building Apps. Claimed in WORKING-NOW.md.

BEGIN;

CREATE OR REPLACE VIEW derm.v_lwt_monthly_rows AS
 SELECT COALESCE(m.white_manifest_number, m.yellow_ticket_number) AS ticket_number,
        CASE
            WHEN m.white_manifest_number IS NOT NULL THEN 'white'::text
            ELSE 'yellow'::text
        END AS ticket_kind,
    m.white_manifest_number IS NOT NULL AS offload_in_dade,
    m.dump_ticket_date AS offload_date,
    df.name AS disposal_facility,
    v.visit_date AS pickup_date,
    c.client_code,
    replace(replace(replace(replace(replace(replace(replace(
      c.name,
      chr(8217), ''''),  -- U+2019 right single quote  (Fialkoff's, NOEL'S)
      chr(8216), ''''),  -- U+2018 left single quote
      chr(8220), '"'),   -- U+201C left double quote
      chr(8221), '"'),   -- U+201D right double quote
      chr(8211), '-'),   -- U+2013 en dash
      chr(8212), '-'),   -- U+2014 em dash
      chr(160),  ' ')    -- U+00A0 non-breaking space
      AS client_name,
    p.address,
    p.city,
    CASE
      WHEN p.state IS NULL THEN NULL
      WHEN upper(btrim(p.state)) IN ('FL','FLORIDA')    THEN 'FL'
      WHEN upper(btrim(p.state)) IN ('CA','CALIFORNIA') THEN 'CA'
      WHEN upper(btrim(p.state)) IN ('NY','NEW YORK')   THEN 'NY'
      WHEN upper(btrim(p.state)) IN ('QC','QUEBEC')
        OR upper(btrim(p.state)) = 'QU' || chr(201) || 'BEC'  THEN 'QC'
      WHEN btrim(p.state) ~ '^[A-Za-z]{2}$'             THEN upper(btrim(p.state))
      ELSE btrim(p.state)   -- unrecognised passes through VERBATIM, never coerced
    END AS state,
    p.zip,
    p.county,
    COALESCE(p.county = 'Dade'::text, false) AS pickup_in_dade,
    COALESCE(p.county = 'Dade'::text, false) OR m.white_manifest_number IS NOT NULL AS in_scope,
    ve.name AS truck,
    ve.grease_tank_capacity_gallons AS truck_capacity_gallons,
    NULL::integer AS gallons,
    m.id AS manifest_id,
    v.id AS visit_id
   FROM derm_manifests m
     JOIN manifest_visits mv ON mv.manifest_id = m.id
     JOIN visits v ON v.id = mv.visit_id AND v.deleted_at IS NULL
     JOIN clients c ON c.id = m.client_id
     LEFT JOIN properties p ON p.id = v.property_id
     LEFT JOIN vehicles ve ON ve.id = v.vehicle_id
     LEFT JOIN disposal_facilities df ON df.id = m.disposal_facility_id
  WHERE m.deleted_at IS NULL;

COMMENT ON VIEW derm.v_lwt_monthly_rows IS
  'One row per PICKUP ACTIVITY for the Miami-Dade LWT monthly filing, served by rpa-derm-monthly. in_scope = pickup county is Dade OR the ticket offloaded in Miami-Dade, evaluated PER ROW because 20 tickets mix counties. pickup_date is visits.visit_date and NEVER derm_manifests.service_date, a misnomer holding the dump date. gallons is always null by contract: the filed quantity is truck capacity resolved from the decal caller-side. state is mapped to USPS two-letter by an EXPLICIT list with unrecognised values passing through verbatim, so a non-Florida property can never be silently relabelled on a compliance form. client_name has typographic punctuation folded to ASCII; accented LETTERS are deliberately preserved because they are the correct spelling (Chateau, Espanola Way) and stripping them would misspell a regulator-facing document.';

COMMIT;

-- VERIFY (run after applying)
--
-- 1. state is uniform, and nothing was invented
--    select coalesce(state,'(null)') state, count(*) from derm.v_lwt_monthly_rows group by 1;
--    -- expect only 'FL' and '(null)'. The nulls are rows whose visit has no property.
--
-- 2. 🛑 THE TOTALS MUST NOT MOVE. This is a presentation change; if row_count or
--    in_scope shifts, a JOIN or the WHERE was altered while the body was regenerated.
--    select count(*) all_rows, count(*) filter (where in_scope) in_scope
--      from derm.v_lwt_monthly_rows;
--    -- expect exactly what it was before applying (690 / 589 on 2026-08-25)
--
-- 3. 🛑 PUNCTUATION GONE, ACCENTS KEPT. Both halves matter and the second is the one
--    that would be a regression rather than an improvement.
--    select count(*) filter (where client_name like '%' || chr(8217) || '%') curly,
--           count(*) filter (where client_name ~ '[^\x20-\x7E]')             name_nonascii,
--           count(*) filter (where address ~ '[^\x20-\x7E]')                 addr_nonascii
--      from derm.v_lwt_monthly_rows;
--    -- expect curly = 0
--    -- expect name_nonascii = 2   (Fendi Chateau Residences -- the a-circumflex SURVIVES)
--    -- expect addr_nonascii = 10  (Espanola Way -- the n-tilde SURVIVES)
--    ⚠ name_nonascii = 0 or addr_nonascii = 0 means the accents were stripped and a real
--      street and a real business are now misspelled on a county form. That is a
--      REGRESSION, not a tidier result.
--
-- 4. NEGATIVE CONTROL that the state mapping is a MAPPING and not a constant. It is
--    latent today, so assert the branch rather than waiting for a Quebec pickup:
--    select (select state from derm.v_lwt_monthly_rows limit 1) as sample,
--           pg_get_viewdef('derm.v_lwt_monthly_rows'::regclass, true) ~ 'CALIFORNIA' as maps_ca,
--           pg_get_viewdef('derm.v_lwt_monthly_rows'::regclass, true) ~ 'ELSE btrim' as passes_through;
--    -- expect maps_ca and passes_through both true
--
-- 5. the endpoint still agrees with the view for every month of 2026 (the standing
--    cross-validation), and data_quality.checked is still true
