-- 2026-08-25_0400_lwt_state_and_punctuation_normalisation.sql
-- ---------------------------------------------------------------------------
-- Normalise what prints on the Miami-Dade LWT monthly form: the state abbreviation,
-- and typographic punctuation in client names.
--
-- Fred: "yes normalise both", after the endpoint status showed `state` arriving as
-- BOTH "FL" and "Florida", and typographic apostrophes in client names.
--
-- Measured before applying, and these are the numbers the VERIFY block asserts against:
--   690 rows / 589 in_scope / 126 tickets
--   state:  Florida 663 · FL 13 · null 14
--   curly apostrophe: 9 rows across 3 distinct names
--     Florida Food Eats LLC Fialkoff’s (Miami Beach) · (Surfside) · NOEL’S KIWI KITCHEN MIAMI BEACH
--   other non-ASCII in a NAME: 2 rows, 1 name -- "Fendi Château Residences"  <- MUST SURVIVE
--   non-ASCII in an ADDRESS:  10 rows -- "Española Way"                    <- MUST SURVIVE
--
-- 🛑 THE OBVIOUS IMPLEMENTATION OF THE FIRST WOULD FALSIFY A COMPLIANCE FORM.
--    `state = 'FL'` is the one-liner, and public.properties holds SIX values:
--        Florida 868 · FL 41 · California 5 · Québec 2 · New York 1 · fl 1
--    (LIVE rows only, deleted_at IS NULL. The raw table reads Florida 869 · FL 43.)
--    ⚠ The stored value really is "Québec" with U+00E9, bytes 5175c3a9626563 -- that is what
--      the chr(201) arm of the CASE exists for. Do not "tidy" it to ASCII and delete that arm.
--    Only Florida/FL/null reach this view TODAY, so a constant would look correct and
--    would silently relabel a Quebec or California property the first time one took a
--    Miami-Dade pickup. This maps explicitly, and anything unrecognised passes through
--    VERBATIM so it is visible rather than quietly wrong.
--
-- 🛑 THE SECOND IS NARROWER THAN IT SOUNDS: ACCENTED LETTERS ARE NOT NOISE, THEY ARE
--    THE CORRECT SPELLING. The non-ASCII here splits cleanly and only one half is an
--    artifact:
--        U+2019 curly apostrophe -> Fialkoff's, NOEL'S            ARTIFACT, normalised
--        U+00E2 in "Chateau", U+00F1 in "Espanola Way"            CORRECT, left alone
--    "Espanola Way" is a real Miami Beach street and "Fendi Chateau Residences" is the
--    business's registered name. Stripping those MISSPELLS a regulator-facing document,
--    which is worse than the inconsistency being fixed. So: punctuation only, and
--    `address` is deliberately NOT touched. Measured over all 921 property rows its non-ASCII is
--    U+00F1 (Española Way, 6 rows) AND U+00E8 (the two Québec addresses, 2 rows) -- both are
--    correct-spelling LETTERS, neither is foldable.
--
-- ⚠ PRESENTATION ONLY. `public.properties.state` and `public.clients.name` are
--   untouched, so every other app still shows what it always showed. Fixing it at
--   source would touch the Field Portal, the Client App and every work order, and is a
--   separate decision.
--
-- ⚠ Measured: `derm.v_lwt_monthly_rows` has ZERO dependent views and `rpa-derm-monthly`
--   selects `*`, so no caller needs editing. Column list unchanged, so CREATE OR
--   REPLACE works and no grant is lost.
--
-- ---------------------------------------------------------------------------
-- HOW THIS BODY WAS PRODUCED, because two separate transports corrupted it first and
-- both are worth knowing:
--
-- It was generated by substituting exactly two lines into live `pg_get_viewdef`
-- output (scratchpad genlwt.js), never retyped -- CREATE OR REPLACE takes the whole
-- body, so anything not reproduced is silently deleted.
--
-- 🛑 (1) `U&'\2019'` ARRIVED AS `U&'9'`. Unicode escapes get eaten in transit through
--     shell/JS string handling. `chr(8217)` is pure ASCII in the source and cannot be
--     damaged, so the substitution uses chr() throughout.
-- 🛑 (2) `String.prototype.replace` INTERPRETS `$&`, `` $` ``, `$'` AND `$1` IN THE
--     REPLACEMENT TEXT. The state branch contains the regex `'^[A-Za-z]{2}$'`, and
--     that `$'` means "everything after the match" -- it spliced the entire remainder
--     of the view back in, turning 31 lines into 68 with a duplicated FROM clause and
--     a truncated regex. **Use a function replacement, `.replace(a, () => b)`**, which
--     is taken literally. The tell was a line delta of +37 against a predicted +19;
--     without that prediction it would have applied and silently changed the view.
--
-- Audit (Rule 8): one view body. No table, column or grant on any audited table
-- changes.
--
-- @Building Apps. Claimed in WORKING-NOW.md.

BEGIN;

CREATE OR REPLACE VIEW derm.v_lwt_monthly_rows AS
 SELECT COALESCE(m.white_manifest_number, m.yellow_ticket_number) AS ticket_number,
        CASE
            WHEN m.white_manifest_number IS NOT NULL THEN 'white'::text
            ELSE 'yellow'::text
        END AS ticket_kind,
    m.white_manifest_number IS NOT NULL AS offload_in_dade,
    m.dump_ticket_date AS offload_date,
    df.name AS disposal_facility,
    v.visit_date AS pickup_date,
    c.client_code,
    replace(replace(replace(replace(replace(replace(replace(
      c.name,
      chr(8217), ''''),  -- U+2019 right single quote  (Fialkoff's, NOEL'S)
      chr(8216), ''''),  -- U+2018 left single quote
      chr(8220), '"'),   -- U+201C left double quote
      chr(8221), '"'),   -- U+201D right double quote
      chr(8211), '-'),   -- U+2013 en dash
      chr(8212), '-'),   -- U+2014 em dash
      chr(160),  ' ')    -- U+00A0 non-breaking space
      AS client_name,
    p.address,
    p.city,
    CASE
      WHEN p.state IS NULL THEN NULL
      WHEN upper(btrim(p.state)) IN ('FL','FLORIDA')    THEN 'FL'
      WHEN upper(btrim(p.state)) IN ('CA','CALIFORNIA') THEN 'CA'
      WHEN upper(btrim(p.state)) IN ('NY','NEW YORK')   THEN 'NY'
      WHEN upper(btrim(p.state)) IN ('QC','QUEBEC')
        OR upper(btrim(p.state)) = 'QU' || chr(201) || 'BEC'  THEN 'QC'
      WHEN btrim(p.state) ~ '^[A-Za-z]{2}$'             THEN upper(btrim(p.state))
      ELSE btrim(p.state)   -- unrecognised passes through VERBATIM, never coerced
    END AS state,
    p.zip,
    p.county,
    COALESCE(p.county = 'Dade'::text, false) AS pickup_in_dade,
    COALESCE(p.county = 'Dade'::text, false) OR m.white_manifest_number IS NOT NULL AS in_scope,
    ve.name AS truck,
    ve.grease_tank_capacity_gallons AS truck_capacity_gallons,
    NULL::integer AS gallons,
    m.id AS manifest_id,
    v.id AS visit_id
   FROM derm_manifests m
     JOIN manifest_visits mv ON mv.manifest_id = m.id
     JOIN visits v ON v.id = mv.visit_id AND v.deleted_at IS NULL
     JOIN clients c ON c.id = m.client_id
     LEFT JOIN properties p ON p.id = v.property_id
     LEFT JOIN vehicles ve ON ve.id = v.vehicle_id
     LEFT JOIN disposal_facilities df ON df.id = m.disposal_facility_id
  WHERE m.deleted_at IS NULL;

COMMENT ON VIEW derm.v_lwt_monthly_rows IS
  'One row per PICKUP ACTIVITY for the Miami-Dade LWT monthly filing, served by rpa-derm-monthly. in_scope = pickup county is Dade OR the ticket offloaded in Miami-Dade, evaluated PER ROW because 20 tickets mix counties. pickup_date is visits.visit_date and NEVER derm_manifests.service_date, a misnomer holding the dump date. gallons is always null by contract: the filed quantity is truck capacity resolved from the decal caller-side. state is mapped to USPS two-letter by an EXPLICIT list with unrecognised values passing through verbatim, so a non-Florida property can never be silently relabelled on a compliance form. client_name has typographic punctuation folded to ASCII; accented LETTERS are deliberately preserved because they are the correct spelling (Chateau, Espanola Way) and stripping them would misspell a regulator-facing document.';

COMMIT;

-- ---------------------------------------------------------------------------
-- 🛑 SUPERSEDED. DO NOT RUN THIS BLOCK. IT GOES RED ON A HEALTHY DATABASE.
--
--    It pins `all_rows <> 690 OR in_scope <> 589 OR tickets <> 126` and `st_fl <> 676`, which
--    were the true values on 2026-08-25 and stopped being true the same morning, when Diego
--    filed ticket 833813 and ten legitimate rows appeared. Running it now reports
--    "[TOTALS MOVED: 700/599/127, expected 690/589/126]" -- a green database described as broken.
--
--    ⇒ **THE CANONICAL, GROWTH-PROOF BLOCK IS IN
--      `docs/migrations/2026-08-25_1500_lwt_normalizer_grant_and_category_close.sql`.**
--      It compares the view against an INDEPENDENT BASE-TABLE RECOMPUTATION at the same instant
--      instead of against a remembered number, asserts state structurally, names the accent
--      CARRIERS rather than counting them, and SET ROLEs to pg_read_all_data for the privilege
--      check. Mutation-tested; it RAISES its own check count on success, which is why no
--      number is quoted here -- the count is data-dependent and a pinned one goes stale.
--
--    The pinned assertions below are LEFT AS WRITTEN on purpose: this file is a dated record of
--    what was asserted when it was applied, and rewriting it would falsify that. But the
--    "run it any time" promise underneath was wrong within hours, so it is withdrawn here.
--
--    🛑 THE LESSON, which this estate had already written down one day earlier in
--       2026-08-25_0110 and which I then did the opposite of:
--       **do not hard-code an expected breakdown against live data.** Compare two live reads of
--       the same instant. A re-runnable check that fails on normal business activity is worse
--       than no check -- it trains whoever runs it to ignore a red result.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- VERIFY -- RE-RUNNABLE AND IT ACTUALLY ASSERTS.
--
-- 🛑 The first version of this block was entirely `--` comments saying "expect 690".
--    Nothing would have failed if the totals HAD moved, despite the header above insisting
--    THE TOTALS MUST NOT MOVE. An audit caught it. A comment is not a control -- this estate
--    has now been bitten by that exact shape three times (a caveat in a view comment while 39
--    wrong bands passed the check; a `RAISE`-less expectation here). If you add an expectation,
--    make it raise.
--
-- Run it any time. It is read-only and takes no arguments.
-- ---------------------------------------------------------------------------
DO $verify$
DECLARE
  r         record;
  v_fail    text := '';
  v_checks  int  := 0;
BEGIN
  SELECT count(*)                                                     AS all_rows,
         count(*) FILTER (WHERE in_scope)                             AS in_scope,
         count(DISTINCT ticket_number)                                AS tickets,
         count(*) FILTER (WHERE client_name LIKE '%'||chr(8217)||'%') AS curly,
         count(*) FILTER (WHERE client_name ~ '[^\x20-\x7E]')         AS name_nonascii,
         count(*) FILTER (WHERE address ~ '[^\x20-\x7E]')             AS addr_nonascii,
         count(*) FILTER (WHERE state IS NOT NULL
                            AND state !~ '^[A-Z]{2}$')                AS state_not_2letter,
         count(*) FILTER (WHERE state = 'FL')                         AS st_fl,
         count(*) FILTER (WHERE state IS NULL)                        AS st_null
    INTO r
    FROM derm.v_lwt_monthly_rows;

  -- 1. the totals must not move. A presentation change that alters these means a JOIN or the
  --    WHERE was damaged while the body was regenerated -- the CREATE OR REPLACE failure mode.
  v_checks := v_checks + 1;
  IF r.all_rows <> 690 OR r.in_scope <> 589 OR r.tickets <> 126 THEN
    v_fail := v_fail || format(' [TOTALS MOVED: %s/%s/%s, expected 690/589/126]',
                               r.all_rows, r.in_scope, r.tickets);
  END IF;

  -- 2. the fold did its job
  v_checks := v_checks + 1;
  IF r.curly <> 0 THEN
    v_fail := v_fail || format(' [%s curly apostrophes still served]', r.curly);
  END IF;

  -- 3. 🛑 THE ACCENTS MUST SURVIVE. This is the assertion that would catch someone
  --    "improving" the fold into unaccent() or a [^\x20-\x7E] strip. A result of ZERO here is
  --    a REGRESSION, not a cleaner one: it means "Fendi Château Residences" and "Española Way"
  --    are now MISSPELLED on a Miami-Dade compliance form.
  v_checks := v_checks + 1;
  IF r.name_nonascii <> 2 OR r.addr_nonascii <> 10 THEN
    v_fail := v_fail || format(' [ACCENTS: name=%s (want 2), addr=%s (want 10) -- if either is 0 a real business name and a real street are now misspelled on a county form]',
                               r.name_nonascii, r.addr_nonascii);
  END IF;

  -- 4. state is uniform, and nothing was invented
  v_checks := v_checks + 1;
  IF r.st_fl <> 676 OR r.st_null <> 14 THEN
    v_fail := v_fail || format(' [STATE: FL=%s (want 676), null=%s (want 14)]', r.st_fl, r.st_null);
  END IF;

  -- 5. 🛑 THE PASS-THROUGH TRIPWIRE. Verbatim pass-through is deliberate and is the reason a
  --    non-Florida property can never be silently relabelled -- but a value reaching the form
  --    that is not a 2-letter code is something a HUMAN must see before it is filed.
  v_checks := v_checks + 1;
  IF r.state_not_2letter <> 0 THEN
    v_fail := v_fail || format(' [%s rows carry a non-2-letter state -- an unrecognised value is passing through to a county filing; look at it, do not coerce it]',
                               r.state_not_2letter);
  END IF;

  -- 6. the mapping is a MAPPING, not a constant. Asserted by OUTCOME against the LIVE view,
  --    because `pg_get_viewdef(...) ~ 'CALIFORNIA'` stays TRUE even with the arm deleted.
  --
  -- 🛑 THE PROBE WRITES, SO IT MUST ROLL BACK, AND A BARE `DO` BLOCK COMMITS ON SUCCESS.
  --    The first version of this restored the value by hand and called itself read-only. It was
  --    not: the updated_at trigger still fired and it left 8 UPDATE rows in audit.logs
  --    (app_source='sql') on the carrier property. Restoring a VALUE is not the same as not
  --    having written. A BEGIN..EXCEPTION block is an implicit SAVEPOINT, so raising a sentinel
  --    at the end of it rolls the writes back -- while PL/pgSQL LOCAL VARIABLES keep the values
  --    they had when the error was raised, which is what lets the results survive the rollback.
  DECLARE
    v_prop bigint; v_vis bigint; v_orig text; v_got text; v_qc text;
    v_cases text[][] := ARRAY[['Florida','FL'],['fl','FL'],['California','CA'],['New York','NY'],
                              ['tx','TX'],['Ontario','Ontario'],['XYZZY','XYZZY']];
  BEGIN
    SELECT x.visit_id, v.property_id INTO v_vis, v_prop
      FROM derm.v_lwt_monthly_rows x JOIN public.visits v ON v.id = x.visit_id
     WHERE v.property_id IS NOT NULL ORDER BY x.visit_id LIMIT 1;
    SELECT state INTO v_orig FROM public.properties WHERE id = v_prop;
    SELECT state INTO v_qc   FROM public.properties WHERE state ILIKE 'qu%bec%' LIMIT 1;

    BEGIN
      FOR i IN 1 .. array_length(v_cases,1) LOOP
        UPDATE public.properties SET state = v_cases[i][1] WHERE id = v_prop;
        SELECT state INTO v_got FROM derm.v_lwt_monthly_rows WHERE visit_id = v_vis LIMIT 1;
        v_checks := v_checks + 1;
        IF v_got IS DISTINCT FROM v_cases[i][2] THEN
          v_fail := v_fail || format(' [MAP %L -> %L, wanted %L]', v_cases[i][1], v_got, v_cases[i][2]);
        END IF;
      END LOOP;

      -- the STORED accented Québec (U+00E9), whose arm depends on upper() under the db collation.
      -- Read from the table, never retyped: a retyped copy tests your editor, not the data.
      IF v_qc IS NOT NULL THEN
        UPDATE public.properties SET state = v_qc WHERE id = v_prop;
        SELECT state INTO v_got FROM derm.v_lwt_monthly_rows WHERE visit_id = v_vis LIMIT 1;
        v_checks := v_checks + 1;
        IF v_got IS DISTINCT FROM 'QC' THEN
          v_fail := v_fail || format(' [the STORED accented Quebec mapped to %L, not QC -- the chr(201) arm is dead under this collation]', v_got);
        END IF;
      END IF;

      RAISE EXCEPTION 'LWT_PROBE_ROLLBACK';       -- undo every write above
    EXCEPTION WHEN raise_exception THEN
      IF SQLERRM <> 'LWT_PROBE_ROLLBACK' THEN RAISE; END IF;   -- a real error still propagates
    END;

    -- prove the rollback actually happened rather than assuming it
    v_checks := v_checks + 1;
    IF (SELECT state FROM public.properties WHERE id = v_prop) IS DISTINCT FROM v_orig THEN
      v_fail := v_fail || format(' [ROLLBACK FAILED: properties.id=%s is not %L]', v_prop, v_orig);
    END IF;
  END;

  IF v_fail <> '' THEN
    RAISE EXCEPTION 'LWT VERIFY FAILED (% checks):%', v_checks, v_fail;
  END IF;
  RAISE NOTICE 'LWT VERIFY: % checks passed', v_checks;
END $verify$;

-- Mutation-tested 2026-08-25, because an assertion that has never failed is an untested
-- instrument. Each of these was made to FAIL on purpose and did:
--   totals 690 -> 691                      -> [TOTALS MOVED: ...]
--   addr_nonascii 10 -> 0                  -> [ACCENTS: ...]
--   expect 'Ontario' -> 'FL'               -> [MAP 'Ontario' -> 'Ontario', wanted 'FL']
--   invert the Quebec comparison           -> [the STORED accented Quebec mapped to 'QC' ...]
-- Mutation C matters most: it proves a failure recorded INSIDE the probe survives the rollback.
-- 14 checks pass against the live view, and properties.updated_at does not move.
--
-- ⚠ STILL NOT ASSERTED HERE, stated so a clean run is not over-read:
--   - `v.deleted_at IS NULL` / `m.deleted_at IS NULL` are unexercised. 0 of 690 linked visits are
--     soft-deleted, so a perturbation control returns 690 vs 690 and DOES NOT FIRE. Those clauses
--     rest solely on byte-identity with the pre-change body, which does hold.
--   - The acceptance test in the design spec ("diff a month against Diego's filed county page") has
--     NOT been re-run. This block proves the database and the endpoint agree; it cannot say what the
--     paper says.
--   - The other nine served string columns are unfolded. Only client_name is watched.
