-- =====================================================================
-- 2026-08-03_1945  DUMP app: hide visits already selected onto a generated DERM sheet
-- =====================================================================
-- WHY
--   Yannick generated a FOG eManifest (sheet 1063) covering five 07-23 visits, then asked why those
--   visits were still offered in the DUMP driver tool. Fred's ruling:
--     "Don't care if they don't show up on the Dump App (i do if they don't show up on the DERM App
--      tho) because they were selected on a generated manifest. That's the logic we want. The Dump
--      App selection of visits is to help on the Manifests linking, it's a helper tool no need to be
--      perfect, it just needs to help."
--
-- WHAT THIS CHANGES, AND WHAT IT DELIBERATELY DOES NOT
--   Both screens were fed by ONE view: public.manifest_pickable_visits. DERM Tracker's "Missing Docs"
--   reads it directly; public.dump_outstanding_visits is built FROM it.
--   ⇒ The exclusion is added HERE ONLY. manifest_pickable_visits is UNTOUCHED.
--   ⇒ DERM Tracker keeps listing a sheet-assigned visit as outstanding until the sheet comes back
--     from the city and a manifest is actually filed. That is intentional: a sheet can be generated
--     and never returned, and hiding it from the compliance screen would be a false all-clear of
--     exactly the kind the DERM 2-week rule exists to catch. The 14-day `needs_office` clock keeps
--     running regardless.
--
-- MEASURED BEFORE (2026-08-03): 8 outstanding visits, of which 3 were already on a live generated
--   sheet and still being offered to drivers:
--       061-TCE visit 6092  sheet 1073  generated 07-30 16:16
--       042-MT  visit 6039  sheet 1073  generated 07-30 16:16
--       062-TCE visit 6104  sheet 1073  generated 07-30 16:16
--   Those three now drop out of the DUMP list. DERM Tracker still shows all 8.
--
-- ⚠ THIS DOES NOT FIX YANNICK'S FIVE, AND THAT IS NOT A BUG IN THIS MIGRATION.
--   Sheet 1063 has NO ROW in derm.address_sheets — never inserted, zero audit rows mention it. The
--   persisted sheets run 1064..1079 starting 07-28 16:23, so 1063 predates the point where the
--   generator began writing a row. There is nothing in the database to exclude on. Those five will
--   keep appearing in BOTH apps until either a manifest is filed or the sheet is regenerated by the
--   current (persisting) generator.
--   ⇒ The general lesson: this exclusion can only ever be as good as the generator's persistence.
--     A generated sheet that writes no row is invisible to every downstream consumer.
--
-- ⚠ NAME COLLISION TO KNOW ABOUT: this view already has a column called `on_sheet`, and it means
--   something ELSE — the DUMP driver's own handout tick from public.dump_manifest_handout (1 row in
--   the whole table). It is NOT the DERM address sheet. Do not merge the two concepts.
--
-- GRANTS: CREATE OR REPLACE preserves them (unlike DROP+CREATE). This view carries a
--   `yannick_readonly` grant on top of service_role — asserted below.
--
-- AUDIT OPT-IN (rule #8): view only, no table change.
-- REVERSIBLE: yes — drop the WHERE clause; column list unchanged.
-- =====================================================================

begin;

create or replace view public.dump_outstanding_visits as
SELECT p.visit_id,
    p.client_code,
    p.client_name,
    regexp_replace(p.address, ',\s*USA.*$'::text, ''::text, 'i'::text) AS address,
        CASE
            WHEN ((p.city IS NOT NULL) AND (regexp_replace(p.address, ',\s*USA.*$'::text, ''::text, 'i'::text) ~* ((',\s*'::text || p.city) || '(\s*,|\s*$)'::text))) THEN NULL::text
            ELSE p.city
        END AS city,
    p.visit_date,
    p.completed_at,
    vis.vehicle_id,
    veh.name AS truck,
    gd.gdo_number,
    GREATEST(0, (((now() AT TIME ZONE 'America/New_York'::text))::date - p.visit_date)) AS age_days,
    (GREATEST(0, (((now() AT TIME ZONE 'America/New_York'::text))::date - p.visit_date)) > 14) AS needs_office,
    (h.visit_id IS NOT NULL) AS on_sheet,
    emp.full_name AS marked_by,
    h.handed_at AS marked_at,
    vis.assigned_driver_id,
    p.county,
    fn_dump_county_bucket(p.county) AS county_bucket,
    ((h.visit_id IS NOT NULL) AND (h.handed_at < (now() - '06:00:00'::interval))) AS confirmed_hidden,
    h.dump_visit_id AS marked_dump_visit_id
   FROM (((((manifest_pickable_visits p
     JOIN visits vis ON ((vis.id = p.visit_id)))
     LEFT JOIN vehicles veh ON ((veh.id = vis.vehicle_id)))
     LEFT JOIN LATERAL ( SELECT fn_resolve_gdo_number(p.client_id, vis.property_id, p.visit_id) AS gdo_number) gd ON (true))
     LEFT JOIN dump_manifest_handout h ON ((h.visit_id = p.visit_id)))
     LEFT JOIN employees emp ON ((emp.id = h.driver_id)))
  -- Suppress visits already SELECTED onto a generated (not yet filed) DERM address sheet.
  -- Fred 2026-08-03: "Don't care if they don't show up on the Dump App (i do if they don't show up
  -- on the DERM App tho) ... The Dump App selection of visits is to help on the Manifests linking,
  -- it's a helper tool no need to be perfect, it just needs to help."
  -- Deliberately scoped to THIS view only: manifest_pickable_visits is UNCHANGED, so the DERM
  -- Tracker keeps listing them as outstanding until the sheet comes back from the city and a
  -- manifest is actually filed. Hiding them there would be a compliance false-all-clear.
  WHERE (NOT (EXISTS ( SELECT 1
           FROM (derm.address_sheet_clients a
             JOIN derm.address_sheets s ON ((s.id = a.sheet_id)))
          WHERE ((a.visit_id = p.visit_id) AND (s.deleted_at IS NULL)))));

-- ---------------------------------------------------------------------
-- ASSERTIONS
-- ---------------------------------------------------------------------
do $$
declare
  n_dump int; n_derm int; n_leak int; n_hidden int;
begin
  -- 1. THE POINT: no visit on a live generated sheet may remain in the DUMP list.
  select count(*) into n_leak
    from public.dump_outstanding_visits o
   where exists (select 1 from derm.address_sheet_clients a
                   join derm.address_sheets s on s.id = a.sheet_id and s.deleted_at is null
                  where a.visit_id = o.visit_id);
  if n_leak > 0 then
    raise exception '% visit(s) on a generated sheet are STILL in the DUMP list', n_leak;
  end if;

  -- 2. NEGATIVE CONTROL: it must actually have hidden something. If nothing was excluded this
  --    migration is a no-op and assertion 1 passes for the wrong reason.
  select count(distinct a.visit_id) into n_hidden
    from derm.address_sheet_clients a
    join derm.address_sheets s on s.id = a.sheet_id and s.deleted_at is null
   where exists (select 1 from public.manifest_pickable_visits p where p.visit_id = a.visit_id);
  if n_hidden = 0 then
    raise exception 'NEGATIVE CONTROL: nothing was on a generated sheet AND pickable, so this changed nothing';
  end if;
  raise notice 'hidden from the DUMP list: % visit(s)', n_hidden;

  -- 3. THE DERM SIDE MUST BE UNCHANGED. This is the half Fred explicitly cares about.
  select count(*) into n_derm from public.manifest_pickable_visits;
  if n_derm < 8 then
    raise exception 'manifest_pickable_visits dropped to % rows — the DERM screen must NOT lose them', n_derm;
  end if;
  -- and specifically: the sheet-assigned visits must STILL be visible there
  select count(*) into n_leak
    from derm.address_sheet_clients a
    join derm.address_sheets s on s.id = a.sheet_id and s.deleted_at is null
   where exists (select 1 from public.manifest_pickable_visits p where p.visit_id = a.visit_id);
  if n_leak <> n_hidden then
    raise exception 'the DERM screen lost sheet-assigned visits (% of % still visible)', n_leak, n_hidden;
  end if;

  select count(*) into n_dump from public.dump_outstanding_visits;
  raise notice 'DUMP list now % rows; DERM pickable still % rows', n_dump, n_derm;

  -- 4. GRANTS survived (CREATE OR REPLACE should preserve them, but the yannick_readonly one is
  --    unusual enough that a silent loss would surface later as an app permissions bug).
  if not has_table_privilege('service_role','public.dump_outstanding_visits','SELECT') then
    raise exception 'GRANT LOST: service_role';
  end if;
  if not has_table_privilege('yannick_readonly','public.dump_outstanding_visits','SELECT') then
    raise exception 'GRANT LOST: yannick_readonly';
  end if;

  raise notice 'DUMP SHEET-EXCLUSION OK';
end $$;

commit;
