-- 2026-07-20 — FP compliance-doc backlog: 7 receipts vision-classified + 4 sheet extents measured
--
-- TRIGGER (Yan via Fred): "Please look at the FP for 150-KOS. The date is 7/9. It's linked to the
-- manifest but it doesn't show in the FP." Visit uF49IpPjJ6 (id 6736) WAS correctly linked to
-- manifest 1365 (white 830088, dumped 7/14, 6 co-loaded clients) — the numbers rendered but BOTH
-- document cards were placeholders because both FP gates were closed:
--   gate 1 (WWTP receipt card): customer.work_orders.wwtp_receipt_url serves dm.derm_manifest_url
--     ONLY when that URL is classified 'receipt' in derm.receipt_doc_class. The classifier is a
--     periodic vision task (last run 2026-07-10, the original 97/97 pass) — 7 photos uploaded since
--     were unclassified, so their receipt cards were dark.
--   gate 2 (DERM FOG card): customer.work_orders.derm_manifest_url serves derm.redacted_manifest_docs
--     for (manifest, client) — generated only for sheets that are STAMPED (bands) AND have a measured
--     extent in derm.page_block_extents. The 4 recent tickets were neither stamped nor measured.
--
-- DONE IN THIS PASS:
-- 1. Vision-classified ALL 7 outstanding manifest photos (each viewed; per-load disposal receipts,
--    zero rosters, zero upload swaps — same result as the 97/97 pass) and inserted
--    derm.receipt_doc_class rows: tickets 821038, 822415, 829788, 830088, 830310, 830413 (SDWWTP)
--    + Broward septage 308915 (derm/1354). EFFECT: receipt cards live fleet-wide — 539 work orders
--    now show a receipt (150-KOS uF49IpPjJ6 verified: wwtp_receipt_url NOT NULL). Exactly 1 work
--    order remains number-without-receipt (no photo uploaded at all).
-- 2. Measured the 4 new address sheets' full-roster extents (Section B block, generous bounds — the
--    safe direction per the 2026-07-10 v2-leak rule) and inserted derm.page_block_extents:
--      ticket-830088 p1 25.5–62.0 · ticket-829788 p1 26.0–63.0 ·
--      ticket-830310 p1 26.5–65.5 · ticket-830413 p1 25.5–62.5   (source 'vision-pass-2026-07-20')
--
-- REMAINING GATE — YANNICK'S STEP: the 4 tickets are UNSTAMPED (address_row_map rows are auto-matched
-- but stamp_x_pct NULL on all). Until he places stamps in Stamp Studio, bands cannot derive and the
-- redact sweep will not generate the FOG cards. Tickets to stamp: 829788 (3 clients), 830088
-- (6 clients — the one Yan reported), 830310 (1), 830413 (2). Once stamped, everything downstream is
-- automatic (extents already in; the */5 redact-manifest-sweep picks them up).
--
-- ⚠ PROCESS GAP FLAGGED: both the receipt classifier and the extent measurement are manual periodic
-- tasks with no tripwire — new uploads go dark on the FP silently until someone notices (Yan did).
-- Candidate for the fix bundle: a weekly "unclassified photos / unmeasured stamped sheets /
-- stamped-but-unredacted" report, or wire the classification into zero-runs.
--
-- Data inserted via Management API (app-source sql); both tables are service-role/machine-written
-- (ADR-010 audit opt-out class). No schema changes.
--
-- OUTCOME (same day, after Fred stamped): stamps for all 4 tickets landed 14:15Z; bands derived
-- immediately (v_stamp_row_bands, all 6 rows of ticket-830088 line-snapped inside the measured
-- extent). The */5 sweep (fn_request_blackout_sweep -> redact-manifest-sheet, LIMIT 1/run) began
-- generating on its next runs but the queue was ~18 pairs (the 4 new tickets + older stamped
-- sheets) = ~90 min at cron pace, which is why Fred saw nothing after 10 minutes. Drained manually:
-- invoked fn_request_blackout_sweep in a 25s-spaced loop -> 9 more docs in ~4 min; ALL 10 pairs of
-- the 4 newly-stamped tickets generated (830088 complete 14:30:42-14:33:00, incl. 150-KOS 14:32:04;
-- 829788, 830310, 830413 complete). VERIFIED: customer.work_orders uF49IpPjJ6 now serves both docs,
-- and the actual redacted file (redacted/m1365-063107bc7a.jpg) was downloaded + visually checked:
-- only the 150-KOS row is readable; the other 5 clients fully blacked; header/certification intact.
--
-- ⚠ STUCK RESIDUAL (follow-up, not tonight's issue): 8 older stamped+measured pairs remain that the
-- sweep does NOT pick up — tickets 306859 (3 pairs), 813912 (1), 827989 (4). fn_blackout_targets is
-- excluding them via one of its stricter gates (order-consistency / page-identity / staleness
-- fingerprint — not replicable from the outside). Investigate with the gate function's own logic.
--
-- STUCK-RESIDUAL RESOLUTION (Fred: "check the other 8 stuck ones and fix them"): the estimated 8
-- decomposed into exactly THREE genuinely missing docs, each with a different cause:
--   1. 827989 / 007-CC (manifest 1235) — QUARANTINED since the EXIF/page-order era ("wrong-client
--      band shows 052-PV", parked to 2030, 99 attempts). Verified against the CURRENT page-2 image:
--      Cafe Club sits exactly at the stored band (p2, 57.8–63.5) and 052-PV is on page 1 — the page
--      mapping was repaired 07-11 but the quarantine never revisited. Un-parked with an annotated
--      retry note -> regenerated -> OUTPUT VISUALLY VERIFIED (only Cafe Club's row readable) ->
--      FP work order 373dlxXCAC now serves both docs. FIXED.
--   2. 306859 / 242-WYN (manifest 1205, service 6/10) — NO visit exists near 6/10 on either Wynd
--      client (241-WYN's nearest is 6/22). No linked live visit -> the gate correctly skips it, and
--      there is no FP page that could show it. UNDERLYING DATA GAP (missing visit or wrong Wynd
--      attribution — the known Wynd 27/28 open item). Office decision needed; NOT forced.
--   3. 813912 / 041-MB (manifest 913, service+dump 1/15) — only candidate visit is 1291 (1/18),
--      which is AFTER the dump; the trg_ac link guard rightly rejects visit>dump+1d. Either the
--      manifest dates or the visit date is wrong — January-era data. Office review; NOT forced.
-- Remaining pairs from the earlier estimate all have docs (the estimate over-counted shared-folder
-- joins). Standing note: quarantine rows park FOREVER (next_retry 2030) with no review loop — add
-- the error table to the weekly tripwire so repaired-but-parked cases resurface.
