-- ============================================================================
-- 2026-07-23c — SA schedule-gap watchdog (new-client Calendar-lag surface)
-- ============================================================================
-- WHY: Diego reported a new client taking "a whole week" (not the expected ~15 min)
-- to appear on the Calendar. Root cause (diagnosed 2026-07-23): a NEW client's
-- client + job rows sync fast (<5 min via sync-jobber-poll), but a RECURRING
-- client's Calendar visits are GENERATED by us (97% of upcoming visits are
-- source='supabase_cron', only ~1% come straight from Jobber). Generation is gated
-- on jobs.frequency_days > 0 — populated from Jobber's "Frequency" numeric custom
-- field by reconcile-jobs (every 6h), then materialized by sa-visit-generation
-- (daily 10:00 UTC). Both crons are healthy; the automatic worst case is ~1-2 days.
--
-- The real "week" is the ONE human dependency in that chain: if the Frequency
-- custom field is left blank (or set on an old/superseded job, or the title is not
-- "Service Agreement…"), the generator produces NOTHING and the client sits
-- invisible on the Calendar indefinitely — until a person notices. No 7-day case
-- exists in the pipeline's own data (max measured job→first-visit gap = 2.2 days,
-- itself a batch-rollout artifact), which confirms the "week" was a data-entry gap.
--
-- This migration adds an ADDITIVE watchdog that turns that silent gap into a daily
-- surfaced signal. It lists SA jobs that satisfy EVERY structural condition of
-- generate_service_agreement_visits.js's JOB_PREDICATE (title ILIKE 'Service
-- Agreement%' + not [OLD] + not archived + a real non-08 SA/SC line item +
-- ACTIVE/RECURRING coded, non-excluded client) EXCEPT frequency_days > 0, and that
-- currently have NO future visit on the Calendar. That is exactly "a recurring SA
-- whose Frequency field was never set, generating nothing" — Diego's "week".
--
-- SCOPE DECISION (Fred 2026-07-23: "flag SA jobs with no frequency set and zero
-- upcoming visits"): the watchdog flags ONLY the frequency-unset cause. A broader
-- "frequency set but still no future visits" bucket was prototyped and dropped: its
-- first hit (021-GRA Granada, job 21002, an ANNUAL freq=364 aux-cleaning last done
-- 2026-01-09, next due ~2027-01, sitting on the 6-month horizon edge) was a
-- horizon-edge FALSE POSITIVE, and judging that bucket accurately would require
-- replicating the generator's anchor/horizon math in the view — which the generator
-- deliberately keeps single-sourced to avoid drift. frequency-unset needs no such
-- math and has zero false positives.
--
-- A 25h grace (job created > 25h ago) prevents crying wolf on brand-new jobs that
-- simply have not hit their first daily generation cycle yet.
--
-- Nothing existing is modified: NEW view + NEW function + NEW pg_cron job only.
-- No visits/Calendar write, no edge fn, no generator change.
--
-- AUDIT (ADR 010): opt-OUT. No new business base table — a read-only view + a
-- health function whose only write is an append to public.sync_log (already the
-- watchdog log sink for rpa-derm-health / calendar-push-health). No human-editable
-- business data is introduced, so no audit.log_change trigger applies.
-- ============================================================================

-- ─── 1. The gap list — SA generator predicate with frequency INVERTED ───────
CREATE OR REPLACE VIEW public.v_sa_schedule_gaps AS
SELECT
  j.id            AS job_id,
  j.job_number,
  j.title,
  j.frequency_days,
  j.job_status,
  c.id            AS client_id,
  c.client_code,
  c.name          AS client_name,
  c.status        AS client_status,
  j.created_at    AS job_created_at,
  round(extract(epoch FROM (now() - j.created_at)) / 86400.0, 1) AS job_age_days,
  'frequency_unset'::text AS gap_reason
FROM public.jobs j
JOIN public.clients c ON c.id = j.client_id
WHERE (j.frequency_days IS NULL OR j.frequency_days <= 0)   -- INVERSE of generator's freq>0 gate
  AND j.title ILIKE 'Service Agreement%'
  AND j.title NOT ILIKE '%[OLD]%'
  AND COALESCE(j.job_status, '') <> 'archived'
  AND c.status IN ('ACTIVE', 'RECURRING')
  AND c.client_code IS NOT NULL
  AND c.client_code NOT IN ('112-YA', '777-YA', '000-DH')   -- generator EXCLUDED_CLIENT_CODES
  -- a real physical-service (non-08) SA/SC line item → this SA is supposed to roll a truck
  AND EXISTS (
    SELECT 1
    FROM public.line_items lp
    JOIN public.service_line_items slip
      ON slip.code = lpad(substring(btrim(lp.name) FROM '^([0-9]+)'), 2, '0')
    WHERE lp.job_id = j.id
      AND lp.invoice_id IS NULL
      AND slip.reason IN ('Service Agreement', 'Service Call')
      AND slip.code <> '08')
  -- currently NO future schedule on the Calendar
  AND NOT EXISTS (
    SELECT 1
    FROM public.visits v
    WHERE v.job_id = j.id
      AND v.deleted_at IS NULL
      AND v.visit_date >= current_date)
  -- grace: only flag once a job has missed a full daily generation cycle
  AND j.created_at < now() - interval '25 hours'
ORDER BY j.created_at DESC;

COMMENT ON VIEW public.v_sa_schedule_gaps IS
  'Watchdog: recurring Service Agreement jobs whose Jobber "Frequency" custom field was never set (frequency_days NULL/<=0), so the SA generator produces no Calendar schedule. Inverse-on-frequency of generate_service_agreement_visits.js JOB_PREDICATE. This is the "new client took a week to show on the Calendar" cause. Added 2026-07-23c.';

REVOKE ALL ON public.v_sa_schedule_gaps FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.v_sa_schedule_gaps TO service_role;

-- ─── 2. Daily health log (mirrors log_rpa_derm_health / log_calendar_push_health) ──
CREATE OR REPLACE FUNCTION public.log_sa_schedule_gaps()
RETURNS integer LANGUAGE plpgsql AS $$
DECLARE
  n_total int;
  attn    boolean;
  sample  jsonb;
BEGIN
  SELECT count(*) INTO n_total FROM public.v_sa_schedule_gaps;
  attn := n_total > 0;

  SELECT jsonb_agg(jsonb_build_object(
           'client_code', client_code, 'client_name', client_name,
           'job_number', job_number, 'age_days', job_age_days))
    INTO sample
    FROM (SELECT * FROM public.v_sa_schedule_gaps ORDER BY job_age_days DESC LIMIT 15) s;

  INSERT INTO public.sync_log (sync_source, started_at, finished_at, rows_errored, status, details)
  VALUES ('sa-schedule-gap-check', now(), now(), n_total,
          CASE WHEN attn THEN 'attention' ELSE 'ok' END,
          jsonb_build_object('frequency_unset', n_total, 'sample', COALESCE(sample, '[]'::jsonb)));

  RETURN n_total;
END $$;

-- ─── 3. Schedule daily, 10:15 UTC (right after sa-visit-generation at 10:00 UTC) ──
DO $$ BEGIN
  PERFORM cron.unschedule('sa-schedule-gap-check');
EXCEPTION WHEN OTHERS THEN NULL; END $$;

SELECT cron.schedule('sa-schedule-gap-check', '15 10 * * *',
  $cmd$ SELECT public.log_sa_schedule_gaps(); $cmd$);
