-- 2026-05-14d_photo_classifications.sql
--
-- Canonical promotion of the photo before/after sorting work from
-- Yannick's Admin Review App (Sandbox #1) into Prod.
--
-- Audit:        docs/audits/2026-05-14_photo_classifications_audit.md
-- Lovable Q&A:  same audit doc, §5 (answers received 2026-05-14)
--
-- Shape rationale (Option B from the audit):
--   * Standalone canonical table keyed by photo_link_id (1:1 with photo_links).
--   * Carries its own audit cols + headroom (quality_flag, notes).
--   * Does NOT bloat photo_links; preserves photo_links.role (Jobber-axis) untouched.
--
-- This migration is DDL-only. Data backfill (~103 rows from Sandbox #1) is
-- a separate script: scripts/probes/backfill_photo_classifications_from_sandbox.js
-- customer.wo_photos update to expose service_phase is a separate migration (14e).

BEGIN;

-- 1. Canonical table -------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.photo_classifications (
  photo_link_id         BIGINT       PRIMARY KEY REFERENCES public.photo_links(id) ON DELETE CASCADE,
  service_phase         TEXT         NOT NULL CHECK (service_phase IN ('before','after','internal','extra','unknown')),
  classified_by_user_id UUID         NULL,           -- will reference auth.users once Admin Review App ships login
  quality_flag          TEXT         NULL,           -- forward-compat (per Lovable Q8); no values written today
  notes                 TEXT         NULL,           -- forward-compat; no values written today
  id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY,  -- surrogate id for client-side referencing (Lovable's regenerated supabase-js types include `.id` on every row); not the PK
  created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS photo_classifications_id_idx ON public.photo_classifications(id);

COMMENT ON TABLE public.photo_classifications IS
  'Human-classified service phase per photo_links row (1:1 with photo_links.id). Source: Yannick''s Admin Review App via dual-write to Prod + Sandbox #1. See migration 2026-05-14d and docs/audits/2026-05-14_photo_classifications_audit.md.';

COMMENT ON COLUMN public.photo_classifications.photo_link_id IS
  'Identifies the canonical photo_link this classification applies to. PK + FK to photo_links(id) ON DELETE CASCADE.';

COMMENT ON COLUMN public.photo_classifications.service_phase IS
  'Enum: before | after | internal | extra | unknown. Renamed 2026-05-15 (was completion -> internal; added extra). The Admin Review App''s 4 user-facing buttons map to before/after/internal/extra; ''unknown'' is the fallback when an explicit phase isn''t selected. CHECK constraint mirrors the TS PhotoClassification union.';

COMMENT ON COLUMN public.photo_classifications.classified_by_user_id IS
  'auth.users id of the human who classified this photo. NULL when written by the anon role (current state — Admin Review App has no login flow yet). Will populate once auth ships.';

COMMENT ON COLUMN public.photo_classifications.quality_flag IS
  'Free-text quality marker (forward-compat — e.g. ''blurry'', ''dark'', ''reshoot needed''). Zero values written today; reserved for Yannick''s future flag-photo UI. Add a CHECK constraint when the value set stabilizes.';

COMMENT ON COLUMN public.photo_classifications.notes IS
  'Free-text classifier notes (forward-compat). Zero values written today.';

COMMENT ON COLUMN public.photo_classifications.created_at IS
  'Timestamp of the first classification of this photo_link (UTC).';

COMMENT ON COLUMN public.photo_classifications.updated_at IS
  'Auto-bumped to now() on every UPDATE by the photo_classifications_set_updated_at trigger. Never set manually.';

COMMENT ON COLUMN public.photo_classifications.id IS
  'Surrogate identity column added 2026-05-15 because Lovable''s auto-generated supabase-js types reference .id on every row. NOT the primary key — photo_link_id is. Don''t write SQL keyed on this column; use photo_link_id for joins/lookups. Indexed UNIQUE for completeness.';

CREATE INDEX IF NOT EXISTS photo_classifications_service_phase_idx
  ON public.photo_classifications (service_phase);

-- 2. Auto-bump updated_at trigger -----------------------------------------
-- Lovable Q2 flagged the Sandbox table is missing this; install it on the
-- canonical from day one.

CREATE OR REPLACE FUNCTION public.tg_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS photo_classifications_set_updated_at ON public.photo_classifications;
CREATE TRIGGER photo_classifications_set_updated_at
  BEFORE UPDATE ON public.photo_classifications
  FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();

-- 3. RLS + policies --------------------------------------------------------
--
-- DECISION (Fred, 2026-05-14, revised after pushback): anon-now, matching the
-- Sandbox pattern. Data on this table is non-PII (photo_link_id + phase tag);
-- worst-case anon-write damage is mis-tagged photos, recoverable by re-classify.
-- Security hardening for all Prod app tables deferred to a single later pass,
-- after Field Portal + DERM apps ship. Don't re-litigate per-migration.

ALTER TABLE public.photo_classifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY photo_classifications_anon_all
  ON public.photo_classifications
  FOR ALL TO anon
  USING (true) WITH CHECK (true);

CREATE POLICY photo_classifications_authenticated_all
  ON public.photo_classifications
  FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- 4. GRANTs ---------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON public.photo_classifications TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE         ON public.photo_classifications TO anon;
-- ^ Revoked in the future security-hardening pass once apps mature.

COMMIT;

-- Rollback (manual, if needed):
--   BEGIN;
--     DROP TRIGGER IF EXISTS photo_classifications_set_updated_at ON public.photo_classifications;
--     DROP TABLE  IF EXISTS public.photo_classifications;
--     -- tg_set_updated_at() is generic; leave it in place unless no other table uses it.
--   COMMIT;
