-- ============================================================================
-- 2026-07-29f — STAGED, NOT APPLIED — close the DERM storage leak by MOVING the
--               raw sheets to a private bucket (NOT by flipping buckets)
-- ============================================================================
-- ⚠ CORRECTION TO AN EARLIER DRAFT OF THIS FILE. The first version proposed
-- `update storage.buckets set public=false` on all three buckets. THAT WAS WRONG
-- and contradicted a decision Fred already made on 2026-07-02, which I had not
-- re-read: a whole-bucket flip is NOT safe, because `GT - Visits Images` holds
-- ~22,789 NON-DERM visit photos that the apps load publicly on purpose. Flipping
-- it 404s all of them to fix 2,572. The agreed shape is a MOVE of the derm/*
-- objects into a new private bucket, leaving both public buckets public.
-- Re-scoping to the move shrinks the blast radius from "all seven consumers" to
-- exactly TWO. Recording the error because the instinct that caused it — plan
-- from the current state, forget the state was already reasoned about — is the
-- same one that produces the "verify one consumer and generalise" mistake.
--
-- ── THE LEAK (measured 2026-07-29, not asserted) ───────────────────────────
-- Raw DERM address sheets are fetchable with NO key and NO headers, at guessable
-- paths: `manifests/derm/<manifest_id>/address_N.jpg` and
-- `GT - Visits Images/derm/<id>/…`, where manifest ids are sequential integers.
-- Each address sheet lists EVERY co-client on that dump ticket — business name
-- and street address. That is precisely what the FP blackout pipeline exists to
-- stop a customer seeing; the redaction is enforced in the app while the raw
-- sheet stays public by URL.
--
-- ── SCOPE: WHAT MOVES, WHAT STAYS (counted 2026-07-29) ─────────────────────
--   MOVE -> new PRIVATE bucket `derm-docs`
--     GT - Visits Images/derm/*     2,572 objects
--     manifests/derm/*                 97 objects
--   STAY PUBLIC (untouched, and this is the whole point of the move)
--     GT - Visits Images  22,789 visit photos  (FP grids, Admin Review classifier)
--     manifests/redacted/*   544 FP customer-facing FOG sheets
--       ⚠⚠ THE ORIGINAL RATIONALE HERE WAS "HASH-NAMED (`m<id>-<10hex>.jpg`), so
--       NOT enumerable". THAT WAS MEASURED FALSE ON 2026-07-29 — kept visible
--       rather than quietly deleted, because the reasoning error matters more
--       than the line. With ONLY the publishable anon key:
--           POST /storage/v1/object/list/manifests {"prefix":"redacted/"}
--             -> HTTP 200, full pagination returned ALL 544 filenames (6 pages)
--           then GET /object/public/manifests/redacted/<name> with NO KEY
--             -> HTTP 200, image/jpeg, 733,655 bytes
--       Same for `manifests/derm/` (40 id-dirs) and `gdo-permits/gdo/` (all 164).
--       **A hash defeats path-GUESSING; it does nothing against the LIST endpoint.**
--       I had reasoned about one attack (guessing) and called the object safe,
--       without checking whether the index was simply readable. `GT - Visits
--       Images` returns 0 rows to anon LIST, which is exactly why the mistake
--       survived — the bucket I spot-checked behaved the way I assumed.
--       ⇒ FIXED INDEPENDENTLY 2026-07-29g: anon SELECT on `storage.objects` for
--         `manifests` dropped, so LIST now returns 0 while public GET stays 200.
--         These 544 are now back to a genuine 40-bit guessing problem — which is
--         what the original line CLAIMED, and is now actually true.
--       ⇒ Whether they should nonetheless JOIN THE MOVE is Fred's open decision;
--         see the note at the end of this file. Do not treat 29g as settling it.
--     manifests (other)        1 brand asset
--     gdo-permits            164 — separate 2026-06-24 decision, stays public
--
-- ── WHY THE MOVE BREAKS ONLY TWO THINGS ────────────────────────────────────
-- Consumers of the MOVE SET only (verified against live bundles + column counts):
--   derm_manifests.derm_address_url / derm_manifest_url / fog_manifest_url  ~587
--     -> DERM Tracker: already signs via get-derm-doc. SURVIVES.
--     -> send-derm-email: ⛔ BREAKS (see below).
--   customer.work_orders.wwtp_receipt_url  544
--     -> FP WWTP card passes `kind` -> get-derm-doc. SURVIVES.
--   derm.v_stamp_rows.image_url  559
--     -> Stamp Studio: ⛔ BREAKS. Renders DB public URLs straight into <img> and
--        into new Image()+canvas.toBlob() for the ZIP export, with ZERO
--        storage-client calls, so the export breaks as well as the display.
--
-- NOT affected, because they never touch derm/*:
--   FP FOG card       -> customer.work_orders.derm_manifest_url is 562/562
--                        `manifests/redacted/…`, and 0 rows point at derm/*.
--   FP photo grids    -> customer.wo_photos.url is `visits/…`. Stays public.
--   Admin Review      -> visit photos, `visits/…`. Stays public.
--   Visit Calendar    -> gdo-permits. Untouched.
--   Client App        -> gdo-permits permit link untouched; DERM links sign.
--
-- ⚠ This is why the move beats the flip: the objects an anon browser cannot sign
-- keep serving publicly exactly as today, and only service-side consumers touch
-- the private bucket, where service_role can always sign.
--
-- ── ⚠ CORRECTION — WHO CAN SIGN `GT - Visits Images` (I got this wrong first) ──
-- I earlier wrote "GT - Visits Images has no anon SELECT policy, so switching
-- getPublicUrl -> createSignedUrl is NOT a fix." That is TRUE FOR anon ONLY, and
-- I stated it as a property of the BUCKET. Building Apps caught it, and flagged
-- it as unproven rather than asserting the opposite — so it was settled by
-- probe, exercising the policy predicate (`auth.uid() IS NOT NULL`) directly:
--
--   authenticated WITH a real uid   GT - Visits Images -> 25,367 rows visible
--   authenticated WITHOUT a uid     GT - Visits Images ->      0 rows visible
--   anon                            GT - Visits Images ->      0 rows visible
--
-- So the rule is about the ROLE, not the bucket:
--   Field Portal (genuinely anon)  -> cannot sign -> needs the edge proxy.
--   Admin Review / Client App /
--   Visit Calendar (authenticated) -> CAN sign client-side. No proxy needed.
--
-- ⚠ AND THE MIDDLE ROW IS A NEW TRAP. `authenticated` with NO `sub` claim sees
-- ZERO rows — the policy tests `auth.uid() IS NOT NULL`, not the role. So a staff
-- app that calls createSignedUrl before its session hydrates, or with an expired
-- token, gets 0 rows -> `not_found` -> a blank frame, NOT an auth error. Combined
-- with the silent-failure note below, that is a bug that looks like a missing
-- photo. Any staff-side signing must be sequenced after session hydration and
-- must assert on the status code.
--
-- ── THE TWO BLOCKERS, BOTH MUST BE FIXED FIRST ─────────────────────────────
-- 1. ⛔ `send-derm-email/index.ts:162 fetchAttachment()` does a bare
--    `await fetch(url)` with NO auth against the stored public URLs. After the
--    move those URLs point at a private bucket and the fetch 400s, so DERM
--    submissions TO THE CITY silently lose their attachment. This is a
--    COMPLIANCE path. Fix (my lane): resolve via service_role
--    `createSignedUrl` — which works on public buckets too, so it can ship and
--    be verified BEFORE the move, independently.
--    ⚠ Do NOT verify it by sending a real submission. Test attachment RESOLUTION
--    only; a real send needs Fred's explicit in-the-moment OK.
-- 2. ⛔ Stamp Studio must stop rendering `derm.v_stamp_rows.image_url` directly
--    (display + ZIP export). It is authenticated, and `derm-docs` will carry an
--    `{authenticated}` SELECT policy, so a client-side `createSignedUrl` IS a
--    sufficient fix there — unlike the anon cases. Building Apps' lane.
--
-- ── URL REWRITE FORMAT (decided 2026-07-24, keep it) ───────────────────────
-- Keep the `/storage/v1/object/public/<bucket>/<path>` SHAPE and swap only the
-- bucket segment to `derm-docs`. Both get-derm-doc's `toBucketPath()` and the
-- Client App helper derive the bucket FROM the stored string and then re-sign, so
-- this repoints every signing consumer with ZERO frontend parser change.
-- ⚠ PRECISION ON get-derm-doc's HARDCODED BUCKET LIST (the queue doc calls this a
-- blocker; read the code before treating it as one). `toBucketPath()` has TWO
-- branches:
--   1. full URL  -> regex `/object/(?:public|sign)/([^/]+)/(.+)$` — captures ANY
--      bucket from the string, so a rewritten `/object/public/derm-docs/…` URL
--      resolves correctly with NO code change.
--   2. raw `bucket/path` -> iterates a hardcoded ['manifests','GT - Visits Images'].
-- Because the decided rewrite format KEEPS the full-URL shape and only swaps the
-- bucket segment, branch 1 covers the entire move and the hardcoded list is NOT a
-- blocker. It still must be extended with `derm-docs` — but as DEFENCE, for the
-- day the pdf-service starts storing raw `bucket/path` values (its documented
-- future contract). Doing it is cheap; blocking the move on it is wrong, and
-- skipping it entirely leaves a trap for whoever ships the raw-path contract.
--
-- ⚠ SEPARATE, AND A REAL ONE: `kind:'fog'` signs
-- `derm_manifests.fog_manifest_url`, which is a PDF under `derm/*`, while FP's FOG
-- card renders the redacted JPG from `customer.work_orders.derm_manifest_url`
-- (`manifests/redacted/*`). So `'fog'` returns the WRONG ARTIFACT for that card —
-- simply dropping the card's `url` prop would make it call get-derm-doc and get a
-- PDF where a JPG is expected. A new kind (e.g. `'redacted'`) is needed for the FP
-- FOG fix. That fix is NOT a prerequisite for the move (redacted/* stays public),
-- but it IS a prerequisite for the FP card ever signing.
--
-- ── EXECUTION ORDER (each step verifiable on its own) ──────────────────────
--   1. Create `derm-docs` PRIVATE + an {authenticated} SELECT policy.
--   2. Fix send-derm-email to sign via service_role. Verify resolution. (mine)
--   3. Stamp Studio -> createSignedUrl. Verify live. (Building Apps)
--   4. Copy the 2,669 objects into `derm-docs`; verify byte counts match.
--   5. Rewrite the URL columns (bucket segment only).
--   6. Re-verify: DERM Tracker, FP WWTP, Stamp Studio, send-derm-email resolution.
--   7. DELETE the public originals under derm/*.
--   8. Drop the now-unnecessary `Public can read manifests` anon policy.
-- ⚠ VERIFY WITH STATUS CODES, NOT PAGES. FP computes its "Documented" chip from
-- `state==='ready' && !!url` — the URL STRING being truthy, never the fetch
-- succeeding — so a broken document still renders a green DOCUMENTED chip over a
-- dead preview. A page-load smoke test PASSES on a broken state.
--
-- ROLLBACK at any point before step 7: repoint the URL columns back to the public
-- bucket. The originals are still there until step 7, so it is fully reversible.
--
-- AUDIT (ADR 010): storage + URL-column change; no business row semantics change.
--
-- ── ⏸ OPEN DECISION FOR FRED — do the 544 `redacted/*` join the move? ──────
-- Raised because the reason they were excluded turned out to be false (above).
-- Re-decide on accurate facts, not on the old "not enumerable" claim:
--
--   ARGUMENT FOR LEAVING THEM PUBLIC
--     · They are the REDACTED copies — co-clients are already blacked out, which
--       is the entire point of the FP blackout pipeline. The disclosure from one
--       leaked sheet is the viewing client's OWN data, not a third party's.
--     · After 29g they are no longer indexed; reaching one needs a 40-bit guess.
--     · They are served to customers with NO login by design. Moving them private
--       means every FP document render must go through a signing round-trip, and
--       FP is the one surface a paying customer looks at.
--     · Zero work, zero risk, today.
--
--   ARGUMENT FOR MOVING THEM
--     · "Redacted" is a claim about a rendering pipeline, not a guarantee. The
--       2026-07-10 v2 leak proved the blackout CAN be wrong; if a bad sheet ever
--       ships, a public bucket means it is world-readable rather than
--       token-scoped, and unrecallable once a URL is out.
--     · A signed URL EXPIRES. A public URL is permanent — once it leaks via a
--       browser history, referrer, forwarded email or support ticket, it is valid
--       forever. Obscurity does not decay gracefully.
--     · FP already proves the pattern works: its WWTP card renders through
--       `get-derm-doc` today with no login and no customer-visible difference.
--
--   MY RECOMMENDATION: leave them public for now, and revisit only if the FOG
--   card is reworked for other reasons. The redaction means the blast radius of
--   one leaked object is that client's own document; 29g removed the bulk-harvest
--   path; and the cost is a signing round-trip on the customer-facing surface for
--   a marginal gain. This is a judgement about acceptable risk, so it is Fred's
--   to make and I have not acted on it.
-- ============================================================================

-- ⚠ COMMENTED OUT DELIBERATELY. Uncomment step by step, in order, verifying each.
-- The object copy itself is NOT SQL — it runs through the storage API with
-- service_role (a script under scripts/migrations/), because storage.objects
-- rows cannot simply be UPDATEd to a different bucket_id without moving bytes.

/*
-- STEP 1 — create the private bucket + let staff apps sign
insert into storage.buckets (id, name, public)
values ('derm-docs', 'derm-docs', false)
on conflict (id) do nothing;

create policy "Authenticated can read derm docs"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'derm-docs');

-- STEP 5 — rewrite the URL columns (bucket segment ONLY; shape preserved)
-- run AFTER the objects exist in derm-docs and BEFORE deleting the originals
update public.derm_manifests set
  derm_address_url  = replace(replace(derm_address_url,  '/object/public/GT%20-%20Visits%20Images/', '/object/public/derm-docs/'), '/object/public/manifests/', '/object/public/derm-docs/'),
  derm_manifest_url = replace(replace(derm_manifest_url, '/object/public/GT%20-%20Visits%20Images/', '/object/public/derm-docs/'), '/object/public/manifests/', '/object/public/derm-docs/'),
  fog_manifest_url  = replace(replace(fog_manifest_url,  '/object/public/GT%20-%20Visits%20Images/', '/object/public/derm-docs/'), '/object/public/manifests/', '/object/public/derm-docs/')
 where derm_address_url like '%/derm/%' or derm_manifest_url like '%/derm/%' or fog_manifest_url like '%/derm/%';
-- ⚠ the *_extra_urls[] array columns need the same treatment — handle explicitly,
--   a scalar replace() will not touch array elements.

-- STEP 8 — after everything verifies, close the last anon door on manifests
-- drop policy "Public can read manifests" on storage.objects;
-- ⚠ only once nothing anon needs to sign `manifests`; the FP redacted/* sheets
--   are served as PUBLIC urls, not signed, so check that first.
*/
