-- 2026-08-26_1615_lwt_mark_as_reported.sql
--
-- WHY (Jonathan Veras, 2026-08-25, #new-app-issues, thread on p1787661000342979):
--   Reply 1: "option 2, shaped like derm_portal_submissions. One thing to know: this isn't a
--            nice-to-have -- Yan asked for it directly in the meeting, so staff can see a month
--            marked reported once it's filed. Month, filed_at, who filed, and a reference field.
--            On your question: the county gives no confirmation number for the monthly form --
--            none of the six filed months has one ... make the reference nullable."
--   Reply 2: "the flag has to live on the TICKET, not on the month. Header {invoice_id, period,
--            filed_at, confirmation_ref} plus tickets[], idempotent, human-triggered from our
--            /monthly UI after the form is actually filed. The reason: your month= selects on
--            offload date, but our filing window is the invoice package, and packages don't align
--            to months -- SP00013840 runs 06/28-07/25. 'All tickets not yet marked reported'
--            replaces that guesswork, and any difference against the invoice becomes a finding in
--            either direction -- including the reverse case we can't detect today."
--
-- 🛑 WHAT THIS DELIBERATELY IS NOT. Jonathan chose option 2 over option 3 and said why:
--    "I'd rather build the thing you'll actually call than guess at a state machine -- inventing
--     one before the manual process is understood is how you get a schema nobody uses."
--    So there is NO per-ticket status enum, NO partial-filing model, NO correction workflow, and
--    NO resubmission state. A ticket is either recorded on a real filing or it is not. If option 3
--    is ever wanted, it is a new migration, not a column bolted onto this.
--
-- 🛑 THE GRAIN IS THE TICKET, NOT THE MONTH, AND THAT IS THE WHOLE POINT. Filing windows are
--    INVOICE PACKAGES and they straddle month boundaries (SP00013840 = 06/28..07/25). A month-
--    grained flag would have to guess which month a straddling package belonged to, and would be
--    wrong for every package that crosses a boundary. period_start/period_end record the package's
--    real window; they are NOT derived from, and must never be reconciled against, the month=
--    parameter of the GET endpoint.

BEGIN;

-- ============================================================================================
-- 1. The filing header: one row per invoice package actually submitted to the county.
-- ============================================================================================
CREATE TABLE IF NOT EXISTS public.lwt_filings (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Idempotency key, same role as derm_portal_submissions.run_id. A repeat POST carrying a run_id
  -- we already hold returns the existing filing untouched rather than creating a second one.
  run_id            text        NOT NULL,

  -- The county invoice package this filing covers, e.g. 'SP00013840'. Nullable because the
  -- package identifier is not always known at filing time.
  invoice_id        text,

  -- The package's REAL window. Not a month. May straddle month boundaries, and usually does.
  period_start      date        NOT NULL,
  period_end        date        NOT NULL,

  -- When the form was actually submitted to the county, supplied by the caller, not defaulted to
  -- now(): the UI is human-triggered AFTER the filing, so now() would record the click, not the act.
  filed_at          timestamptz NOT NULL,

  -- ⚠ FREE TEXT AND NULLABLE ON PURPOSE. Jonathan: "the county gives no confirmation number for
  -- the monthly form -- none of the six filed months has one." Do not add a format CHECK, do not
  -- make it required, and do not infer a failure from its absence.
  confirmation_ref  text,

  -- Who filed. Mirrors derm_portal_submissions.filed_by_email and its manual-% pairing rule.
  filed_by_email    text,

  dry_run           boolean     NOT NULL DEFAULT false,
  created_at        timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT lwt_filings_run_id_uniq        UNIQUE (run_id),
  CONSTRAINT lwt_filings_run_id_chk         CHECK (run_id ~ '^[A-Za-z0-9_.-]{1,100}$'),
  CONSTRAINT lwt_filings_period_ordered_chk CHECK (period_end >= period_start),
  CONSTRAINT lwt_filings_invoice_id_chk     CHECK (invoice_id IS NULL OR length(invoice_id) <= 100),
  CONSTRAINT lwt_filings_confirmation_chk   CHECK (confirmation_ref IS NULL OR length(confirmation_ref) <= 500),
  -- Same rule derm_portal_submissions uses: a human actor is recorded exactly when the run is a
  -- manual one, so the two markers can never disagree about whether a person did this.
  CONSTRAINT lwt_filings_actor_markers_agree
    CHECK ((filed_by_email IS NOT NULL) = (COALESCE(run_id, '') LIKE 'manual-%'))
);

COMMENT ON TABLE public.lwt_filings IS
  'One row per LWT monthly-form filing (an invoice package submitted to Miami-Dade). Grain is the '
  'PACKAGE, not the month: packages straddle month boundaries. Written only by '
  'rpa-derm-monthly-filed. See docs/migrations/2026-08-26_1615_lwt_mark_as_reported.sql.';

-- ============================================================================================
-- 2. The tickets covered by a filing. This is the "reported" flag Jonathan asked for.
-- ============================================================================================
CREATE TABLE IF NOT EXISTS public.lwt_filing_tickets (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filing_id     bigint      NOT NULL REFERENCES public.lwt_filings(id) ON DELETE CASCADE,

  -- The value the caller sees as ticket_number in the GET payload, i.e.
  -- COALESCE(white_manifest_number, yellow_ticket_number). Stored as given.
  ticket_number text        NOT NULL,

  -- Resolved server-side for referential value. Nullable: a ticket_number that matches no live
  -- manifest is still recorded, because refusing it would lose the fact that it WAS filed.
  manifest_id   bigint      REFERENCES public.derm_manifests(id),

  created_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT lwt_filing_tickets_uniq        UNIQUE (filing_id, ticket_number),
  CONSTRAINT lwt_filing_tickets_number_chk  CHECK (ticket_number ~ '^[A-Za-z0-9_.-]{1,64}$')
);

-- ⚠ A TICKET MAY APPEAR ON MORE THAN ONE FILING, ON PURPOSE. There is no global UNIQUE on
--    ticket_number. A refile or a correction is then simply a second filing that includes it, and
--    "reported" stays a question about EXISTENCE rather than about state. That keeps option 3 out
--    of this schema while leaving the door open. If a ticket must only ever be filed once, that is
--    a policy decision for Yan and a later partial unique index, not something to assume here.
CREATE INDEX IF NOT EXISTS lwt_filing_tickets_ticket_idx  ON public.lwt_filing_tickets (ticket_number);
CREATE INDEX IF NOT EXISTS lwt_filing_tickets_filing_idx  ON public.lwt_filing_tickets (filing_id);
CREATE INDEX IF NOT EXISTS lwt_filing_tickets_manifest_idx ON public.lwt_filing_tickets (manifest_id);

COMMENT ON TABLE public.lwt_filing_tickets IS
  'Which tickets a given LWT filing covered. Presence of a row on a NON-dry-run filing is what '
  '"reported" means. A ticket may appear on more than one filing (a refile); reported is an '
  'existence question, not a state machine.';

-- ============================================================================================
-- 3. The read side: one row per ticket, reported or not.
-- ============================================================================================
-- ⚠ dry_run filings are EXCLUDED from reported. A rehearsal must never make a real ticket look
--    filed. This is the same reason derm_portal_submissions carries dry_run.
CREATE OR REPLACE VIEW derm.v_lwt_ticket_reported AS
SELECT t.ticket_number,
       (f.id IS NOT NULL)  AS reported,
       f.id                AS filing_id,
       f.invoice_id,
       f.period_start,
       f.period_end,
       f.filed_at,
       f.confirmation_ref,
       f.filed_by_email
  FROM (SELECT DISTINCT ticket_number FROM derm.v_lwt_monthly_rows) t
  LEFT JOIN LATERAL (
        -- The most recent REAL filing that covered this ticket. LATERAL + LIMIT 1 rather than a
        -- plain join, so a refiled ticket cannot fan this view out to two rows per ticket.
        SELECT lf.*
          FROM public.lwt_filing_tickets lft
          JOIN public.lwt_filings lf ON lf.id = lft.filing_id
         WHERE lft.ticket_number = t.ticket_number
           AND lf.dry_run = false
         ORDER BY lf.filed_at DESC, lf.id DESC
         LIMIT 1
       ) f ON true;

COMMENT ON VIEW derm.v_lwt_ticket_reported IS
  'One row per distinct LWT ticket_number with its most recent real filing, or reported=false. '
  'LATERAL LIMIT 1 keeps it one row per ticket even when a ticket has been filed twice.';

-- ============================================================================================
-- 4. Grants. Follows the estate rule: REVOKE FROM PUBLIC is not enough, service_role must be
--    granted explicitly (reference_supabase_function_default_privileges).
-- ============================================================================================
REVOKE ALL ON public.lwt_filings         FROM PUBLIC;
REVOKE ALL ON public.lwt_filing_tickets  FROM PUBLIC;

GRANT SELECT, INSERT ON public.lwt_filings        TO service_role;
GRANT SELECT, INSERT ON public.lwt_filing_tickets TO service_role;
GRANT SELECT           ON derm.v_lwt_ticket_reported TO service_role;

-- Staff apps read it; nobody writes it except the edge function via service_role.
GRANT SELECT ON public.lwt_filings           TO authenticated;
GRANT SELECT ON public.lwt_filing_tickets    TO authenticated;
GRANT SELECT ON derm.v_lwt_ticket_reported   TO authenticated;

-- ⚠ NO anon grant. This is compliance data.

COMMIT;
