-- ============================================================================
-- 2026-08-01_0930 — Making a client RECURRING requires a CURRENT-format SA job
-- ============================================================================
-- ASK (Fred, 2026-07-31):
--   "when making a client Recurrent, it forces them to create a SA visit or use
--    one that is open (in case of paused) o closed (inactive or active). But for
--    the ones which are closed, it needs to be the ones with the format we're
--    using for the jobs, so it needs to be like with the SA job, not one of the
--    older ones."
--   and, from the same batch: "remember the 'proof' or 'reason' of why the
--   change of status, we need to save that" (already shipped, 2026-07-31_1520).
--
-- ---------------------------------------------------------------------------
-- WHAT "CURRENT FORMAT" MEANS — MEASURED, NOT ASSUMED
-- ---------------------------------------------------------------------------
-- The eligibility predicate below was derived by scoring every job in the
-- warehouse and checking it against known-good and known-bad examples:
--
--   POSITIVE CONTROL (must all pass) — the live SA jobs on the reference
--   clients: 112-YA #11100534, 063-TCE #99900664, 064-TCE #99900667,
--   021-GRA #21002. All four score eligible.
--
--   NEGATIVE CONTROL (must all fail) — every archived job belonging to the 6
--   PAUSED clients. Measured shape: `frequency_days` IS NULL and ZERO coded
--   line items. Titles are things like 'Grease Trap Pumping', 'Hydrojet
--   Cleaning', 'Service agreement - Grease trap pumping' (4 line items, none
--   coded). These are EXACTLY the "older ones" Fred means, and all 10 fail.
--
-- The load-bearing signal is the CATALOGUE CODE on the line items, not the
-- title: the catalogue only came into use in 2026, so "does it carry coded
-- service lines" is precisely the old/new boundary. Title is a secondary guard.
--
-- ⚠ WARRANTY-ONLY JOBS ARE DELIBERATELY NOT ELIGIBLE, AND THIS IS THE SUBTLE
-- PART. A first cut of this predicate accepted any coded SA job and produced 31
-- "reusable" archived jobs — but 23 of them were `Service Agreement - Warranty
-- of Drainage` carrying ONLY a code-08 line. Warranty of Drainage generates NO
-- recurring visits by design (the generator predicate carries `code <> '08'`),
-- so reusing one would have produced a RECURRING client that never gets a
-- visit — a silent failure of exactly the kind this gate exists to prevent.
-- A job therefore qualifies only if it carries a PUMPING or CLEANING line
-- (codes 01-07), i.e. something that can actually generate a recurring visit.
-- 021-GRA #21002 (cleaning + warranty) still qualifies, on its cleaning line.
--
-- ---------------------------------------------------------------------------
-- WHY THE GATE LIVES IN THE RPC AND NOT IN A TRIGGER
-- ---------------------------------------------------------------------------
-- A BEFORE UPDATE trigger on public.clients would also block the Jobber inbound
-- sync from setting RECURRING. Clients are Jobber-mastered during the bridge
-- (Client App CLAUDE.md rule #2), so a trigger would make the poll fail on
-- legitimate upstream data. The gate is a rule about what a HUMAN may do in the
-- app, so it belongs on the app's write path only. `clients.status` is not
-- otherwise app-writable.
--
-- ---------------------------------------------------------------------------
-- THE REOPEN PATH
-- ---------------------------------------------------------------------------
-- The gate only ever looks for an eligible OPEN (non-archived) job. Reusing a
-- CLOSED one is therefore a two-step the APP drives, in this order:
--     1. reopen the archived job through the `save-client-job` edge function
--        (Jobber jobReopen -> re-read -> verify -> DB), then
--     2. call update_client_status.
-- After step 1 the job is non-archived and the gate passes naturally. This
-- keeps the Jobber write inside the verified saga and out of the RPC, and it
-- honours the standing rule that a Jobber-bound write is never reported as
-- successful until Jobber has been re-read.
--
-- ⚠ VISIT GENERATION IS NOT IMMEDIATE, AND THE UI MUST NOT CLAIM IT IS.
-- SA visits are generated by scripts/sync/generate_service_agreement_visits.js
-- via the GitHub Action `sa-visit-generation.yml` (daily 06:00 ET), NOT by
-- pg_cron and NOT by this RPC. Once a client is RECURRING with an eligible job,
-- the next nightly run creates the chain and the DB trigger pushes it to
-- Jobber. `next_generation_note` in the payload below exists so the dialog can
-- say so honestly instead of implying visits appear on save.
--
-- 3NF / Rule 1: no new columns and no stored state — eligibility is derived at
-- read time from jobs + line_items. Audit (ADR 010): no table shape changes.
-- Grants: EXECUTE to authenticated only; anon and service_role revoked
-- explicitly (Supabase grants new functions to PUBLIC by default).
--
-- ROLLBACK:
--   drop function client.recurring_eligibility(bigint);
--   drop function client.fn_is_current_sa_job(bigint);
--   -- and restore the previous 3-arg update_client_status from 2026-07-31_1520
-- ============================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1. the eligibility predicate, in ONE place so the gate and the picker
--    can never disagree about what "current format" means
-- ---------------------------------------------------------------------------
create or replace function client.fn_is_current_sa_job(p_job_id bigint)
returns boolean
language sql
stable
set search_path = ''
as $$
  select exists (
    select 1
    from public.jobs j
    where j.id = p_job_id
      -- a real recurring agreement
      and coalesce(j.frequency_days, 0) > 0
      -- current naming, and not a migration/test artefact
      and j.title ilike 'Service Agreement%'
      and j.title not ilike '%[OLD]%'
      and j.title not ilike 'TEST%'
      and j.title not ilike '%TEST -%'
      -- and it must be able to GENERATE a recurring visit: a coded pumping or
      -- cleaning line. Warranty-only (08) never generates one.
      and exists (
        select 1
        from public.line_items li
        where li.job_id = j.id
          and li.visit_id is null
          and li.invoice_id is null
          and client.fn_billing_group(li.name) in ('pumping', 'cleaning')
      )
  );
$$;

comment on function client.fn_is_current_sa_job(bigint) is
  'True when a job is a CURRENT-format Service Agreement that can generate recurring visits: frequency_days > 0, title "Service Agreement%" (not [OLD]/TEST), and at least one job-scoped line item coded 01-07 (pumping or cleaning). Warranty-only 08 jobs are excluded on purpose - the visit generator carries code <> ''08'', so a WD-only job would make a client RECURRING with no visits. Legacy pre-2026 jobs fail because they carry no coded line items.';

-- ---------------------------------------------------------------------------
-- 2. what the Edit-client dialog needs to render the choice
-- ---------------------------------------------------------------------------
create or replace function client.recurring_eligibility(p_client_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  with scoped as (
    select j.id, j.job_number, j.title, j.job_status, j.frequency_days,
           j.property_id, j.start_at,
           client.fn_is_current_sa_job(j.id) as eligible,
           (j.job_status = 'archived')       as is_closed
    from public.jobs j
    where j.client_id = p_client_id
  ),
  shaped as (
    select s.*,
      (select coalesce(json_agg(distinct client.fn_billing_group(li.name))
                filter (where client.fn_billing_group(li.name) is not null), '[]'::json)
         from public.line_items li
        where li.job_id = s.id and li.visit_id is null and li.invoice_id is null) as groups
    from scoped s
  )
  select jsonb_build_object(
    'client_id',      p_client_id,
    'client_code',    (select c.client_code from public.clients c where c.id = p_client_id),
    'current_status', (select c.status      from public.clients c where c.id = p_client_id),
    -- an eligible OPEN job means RECURRING can be set with no further action
    'open_eligible', coalesce((
       select jsonb_agg(jsonb_build_object(
                'job_id', id, 'job_number', job_number, 'title', title,
                'job_status', job_status, 'frequency_days', frequency_days,
                'property_id', property_id, 'groups', groups)
              order by frequency_days)
       from shaped where eligible and not is_closed), '[]'::jsonb),
    -- an eligible CLOSED job must be reopened via save-client-job FIRST
    'closed_eligible', coalesce((
       select jsonb_agg(jsonb_build_object(
                'job_id', id, 'job_number', job_number, 'title', title,
                'frequency_days', frequency_days, 'property_id', property_id,
                'groups', groups)
              order by frequency_days)
       from shaped where eligible and is_closed), '[]'::jsonb),
    -- shown as context only: these exist but are NOT offerable
    'legacy_closed_count', (select count(*) from shaped where is_closed and not eligible),
    'can_set_recurring_now', exists (select 1 from shaped where eligible and not is_closed),
    'next_generation_note',
      'SA visits are generated by the nightly run at 06:00 ET, not on save.'
  );
$$;

comment on function client.recurring_eligibility(bigint) is
  'Feeds the Edit-client status dialog: which Service Agreement jobs could make this client RECURRING. open_eligible = set RECURRING directly; closed_eligible = reopen via the save-client-job edge fn FIRST, then set the status; legacy_closed_count = old-format jobs that exist but must not be offered. Read-only.';

-- ---------------------------------------------------------------------------
-- 3. the gate itself, added to the 3-arg (reason-carrying) entry point
-- ---------------------------------------------------------------------------
-- ⚠ THIS IS THE 2026-07-31_1520 BODY WITH ONE BLOCK ADDED. Everything else is
-- reproduced verbatim on purpose. A first draft of this migration rewrote the
-- function from scratch and would have silently broken three things:
--   * the return shape — the app reads `client` (a full to_jsonb(row)), not
--     the flat {client_id, old_status, new_status} a fresh draft produced;
--   * the NO-OP short circuit (v_old = p_status returns early with noop:true),
--     without which a re-save writes a spurious proof row and re-runs the gate;
--   * `visits_removed`, which is a BEFORE/AFTER count of live scheduled future
--     visits — a "deleted_at > now() - 10 seconds" shortcut would also count
--     unrelated deletions and is wall-clock fragile.
-- Diff against 2026-07-31_1520 before editing this again.
create or replace function client.update_client_status(
  p_client_id bigint,
  p_status    text,
  p_reason    text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old    text;
  v_row    public.clients;
  v_before int;
  v_after  int;
  v_removed int;
  v_email  text;
begin
  if auth.uid() is null then
    raise exception 'authentication required' using errcode = '28000';
  end if;
  v_email := lower(coalesce(auth.jwt() ->> 'email',''));
  if v_email not like '%@ayache.com' and v_email not like '%@unclogme.com' then
    raise exception 'not a staff account' using errcode = '42501';
  end if;
  -- PAUSED added 2026-07-31 (Fred). All four states are now settable.
  if p_status is null or p_status not in ('ACTIVE','RECURRING','INACTIVE','PAUSED') then
    raise exception 'status must be ACTIVE, RECURRING, INACTIVE or PAUSED (got %)', p_status
      using errcode = '22023';
  end if;
  -- The proof is the point: no reason, no change.
  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'a reason is required when changing a client''s status'
      using errcode = '22023';
  end if;
  if length(btrim(p_reason)) > 500 then
    raise exception 'reason is too long (500 characters max)' using errcode = '22023';
  end if;

  select c.status into v_old from public.clients c where c.id = p_client_id;
  if v_old is null then
    raise exception 'client % not found', p_client_id using errcode = 'P0002';
  end if;
  if v_old = p_status then
    select c.* into v_row from public.clients c where c.id = p_client_id;
    return jsonb_build_object('client', to_jsonb(v_row), 'visits_removed', 0, 'noop', true);
  end if;

  -- ▼▼▼ ADDED 2026-08-01 — THE ONLY CHANGE ▼▼▼
  -- RECURRING requires a current-format SA job that can actually generate
  -- visits. Without one the client sits in RECURRING forever with an empty
  -- schedule and nothing reports it. Checked AFTER the no-op branch so that
  -- re-saving an already-RECURRING client can never be blocked by it.
  if p_status = 'RECURRING' then
    if not exists (
      select 1 from public.jobs j
      where j.client_id = p_client_id
        and j.job_status <> 'archived'
        and client.fn_is_current_sa_job(j.id)
    ) then
      raise exception
        'cannot set RECURRING: this client has no open Service Agreement job in the current format. Create one, or reopen a closed current-format agreement first.'
        using errcode = '23514';
    end if;
  end if;
  -- ▲▲▲ END OF ADDED BLOCK ▲▲▲

  select count(*) into v_before
    from public.visits v
   where v.client_id = p_client_id and v.deleted_at is null
     and v.visit_status = 'scheduled' and v.visit_date >= current_date;

  update public.clients c set status = p_status
   where c.id = p_client_id
  returning c.* into v_row;          -- AFTER trigger performs the SA cleanup

  select count(*) into v_after
    from public.visits v
   where v.client_id = p_client_id and v.deleted_at is null
     and v.visit_status = 'scheduled' and v.visit_date >= current_date;
  v_removed := greatest(v_before - v_after, 0);

  insert into public.client_status_changes
    (client_id, old_status, new_status, reason, changed_by, changed_by_email, visits_removed)
  values (p_client_id, v_old, p_status, btrim(p_reason), auth.uid(), v_email, v_removed);

  return jsonb_build_object(
    'client', to_jsonb(v_row),
    'previous_status', v_old,
    'visits_removed', v_removed,
    'note', case when p_status = 'RECURRING'
                 then 'SA visits are generated by the nightly run at 06:00 ET, not on save.'
                 else null end);
end;
$$;

-- Supabase grants new/replaced functions to PUBLIC by default — revoke explicitly.
revoke all on function client.fn_is_current_sa_job(bigint)   from public, anon, service_role;
revoke all on function client.recurring_eligibility(bigint)  from public, anon, service_role;
revoke all on function client.update_client_status(bigint, text, text) from public, anon, service_role;

grant execute on function client.fn_is_current_sa_job(bigint)  to authenticated;
grant execute on function client.recurring_eligibility(bigint) to authenticated;
grant execute on function client.update_client_status(bigint, text, text) to authenticated;

commit;
