-- 2026-08-19_2320_generated_sheet_extents_and_blocked_detector.sql
--
-- WHAT: (1) measured extents for three GENERATED address sheets that were stamped but never
--       measured, which is what kept 34 clients' Field Portal FOG eManifest card empty, and
--       (2) a standing detector so this state is visible the day it happens instead of when a
--       client notices a blank card.
--
-- HOW IT SURFACED: Fred, on client 306-16 (16 Handles), visit 8/12/2026 -- "i can't see the
--       blackedout manifest even though is stamped by AI and then manually by us". The stamp was
--       real (ticket-311780, placed 16:56 that day). The MEASUREMENT was missing.
--
-- THE MECHANISM, and it is the documented one: derm.fn_blackout_targets HARD-GATES on a
--       derm.page_block_extents row --
--         JOIN derm.page_block_extents e ON e.dump_folder = l.dump_folder
--                                       AND e.effective_page = l.effective_page
--       so an unmeasured page yields NO target, the */5 redact-manifest-sweep has nothing to do,
--       customer.work_orders.derm_manifest_url stays NULL, and the card is a permanent placeholder.
--       ⚠ NOTHING LOOKS BROKEN while this is true: the sweep cron reports `succeeded` every five
--         minutes because an empty work queue is a successful run. That is why it went unnoticed.
--
-- SCOPE, AND THE DETECTOR CORRECTED MY OWN COUNT BEFORE THIS SHIPPED. My first sweep grouped by
--       dump_folder and asked whether the FOLDER had any extent at all. That found 4 blocked
--       folders. The detector below asks the question the gate actually asks -- is there an extent
--       for THIS (folder, effective_page)? -- and found **5 folders / 8 pages**. The extra one is
--       `window5-sheet3`, which HAS an extent for page 2 and none for page 1, so a folder-level
--       check can never see it. The VERIFY block caught my wrong expectation on the first apply and
--       rolled the whole migration back, which is exactly what it is for.
--       ⇒ A folder-level check is the wrong grain for a page-level gate. Anything measuring this
--         must key on (dump_folder, effective_page) or it under-reports by construction.
--
--       Blocked population: 5 folders, 8 pages, 36 manifests, 35 clients, all with a NULL
--       derm_manifest_url. This migration fixes THREE folders (6 pages, the generated ones).
--       TWO are deliberately left alone because they are SCANNED, not generated, and scanned
--       geometry varies per scan (measured fleet range 23.6-29.4 top, 58.8-66.4 bottom) -- so
--       templating them would be a guess about a customer-facing redaction:
--         ticket-832996  page 1  (no sheet number, 5 clients)
--         window5-sheet3 page 1  (no sheet number, 1 client; page 2 already measured 2026-07-11)
--       Both need a real vision measurement.
--
-- WHY THESE THREE CAN BE TEMPLATED: sheets 1085, 1089 and 1090 are GENERATED by our own
--       pdf-service, so their form geometry is deterministic rather than scan-dependent. The value
--       below is the one already measured for generated sheets and used unchanged since:
--         ticket-310429 p1/p2, ticket-831325 p1  (generated-form-rules-2026-08-03)
--         ticket-831938 p1/p2                     (generated-form-rules-2026-08-07)
--       all of them 25.8 / 64.4. Corroborating shape: every one of the six pages below holds
--       exactly 5 stamped rows, which is the generated sheet's 5-slot roster.
--
-- 🛑 DIRECTION OF RISK: the two blackout boxes are OPAQUE OVERWRITES, so a WIDER extent can only
--    add black. NARROWING is the leak direction -- a roster row above blocks_top or below
--    blocks_bottom is served to the customer as-is, and that is exactly the v2 leak Fred caught on
--    2026-07-10. 25.8/64.4 is at or wider than every generated measurement on file, so this errs
--    toward more redaction, never less.
--
-- 🛑 effective_page IS THE STAMP PAGE, NOT THE ROW PAGE. derm.v_stamp_row_bands defines it as
--    COALESCE(stamp_page, page), and these rows genuinely differ: ticket-311780's 306-16 row is
--    page=1 with stamp_page=2. Keying these inserts on `page` would have written six rows that
--    satisfy nothing, leaving the gate shut while the migration looked applied.
--
-- AUDIT (rule 8): derm.page_block_extents is NOT audited and stays NOT audited (it is derived
--    measurement geometry, re-derivable by a vision pass, and carries no human-editable business
--    field). derm.address_row_map IS audited and is not touched here.

begin;

-- ---- 1. the three generated sheets ------------------------------------------------------------
insert into derm.page_block_extents (dump_folder, effective_page, top_pct, bottom_pct, source, measured_at)
values
  ('ticket-311780', 1, 25.8, 64.4, 'generated-form-rules-2026-08-19', now()),
  ('ticket-311780', 2, 25.8, 64.4, 'generated-form-rules-2026-08-19', now()),
  ('ticket-832487', 1, 25.8, 64.4, 'generated-form-rules-2026-08-19', now()),
  ('ticket-832487', 2, 25.8, 64.4, 'generated-form-rules-2026-08-19', now()),
  ('ticket-833049', 1, 25.8, 64.4, 'generated-form-rules-2026-08-19', now()),
  ('ticket-833049', 2, 25.8, 64.4, 'generated-form-rules-2026-08-19', now())
on conflict (dump_folder, effective_page) do nothing;

-- ---- 2. THE DETECTOR ---------------------------------------------------------------------------
-- A sheet that has been stamped but never measured produces no blackout target and therefore no
-- customer document, silently. This view names that state directly so it can be watched.
--
-- ⚠ IT COUNTS STAMPED ROWS, NOT MANIFESTS, as its trigger. A folder can be fully stamped and still
--   have no measurement; the manifests hanging off it are the CONSEQUENCE, which is why they are
--   reported as impact rather than used as the condition.
create or replace view derm.v_blackout_blocked_sheets as
  select
    arm.dump_folder,
    count(*) filter (where arm.stamp_y_pct is not null)                as stamped_rows,
    count(distinct coalesce(arm.stamp_page, arm.page))
      filter (where arm.stamp_y_pct is not null)                       as stamped_pages,
    count(distinct arm.matched_manifest_id)
      filter (where arm.matched_manifest_id is not null)               as manifests_blocked,
    count(distinct arm.matched_client_id)
      filter (where arm.matched_client_id is not null)                 as clients_blocked,
    max(arm.stamp_placed_at)                                           as last_stamp_at,
    now() - max(arm.stamp_placed_at)                                   as blocked_for,
    'Stamped but never measured: derm.fn_blackout_targets hard-gates on derm.page_block_extents, so no redacted sheet is produced and the Field Portal FOG card stays empty. Run a measurement pass for this folder.'::text as what_to_do
  from derm.address_row_map arm
  where arm.stamp_y_pct is not null
    and not exists (
      select 1 from derm.page_block_extents e
       where e.dump_folder = arm.dump_folder
         and e.effective_page = coalesce(arm.stamp_page, arm.page))
  group by arm.dump_folder;

comment on view derm.v_blackout_blocked_sheets is
  'Address-sheet folders that are stamped but carry no page_block_extents row for a stamped page, so they can never produce a redacted customer document. Empty is the healthy state. Non-empty means those clients see a blank FOG eManifest card in the Field Portal and nothing else reports it: the redact sweep logs success either way, because an empty work queue is a successful run.';

revoke all on derm.v_blackout_blocked_sheets from public, anon;
grant select on derm.v_blackout_blocked_sheets to authenticated, service_role;

-- ---- VERIFY ------------------------------------------------------------------------------------
do $verify$
declare v_ext int; v_targets int; v_still_blocked int; v_wrong_page int;
begin
  select count(*) into v_ext from derm.page_block_extents
   where dump_folder in ('ticket-311780','ticket-832487','ticket-833049');
  if v_ext <> 6 then raise exception 'VERIFY: expected 6 extent rows, found %', v_ext; end if;

  -- THE REAL PROOF: the gate must now open. It returned 0 for these folders before this migration.
  select count(*) into v_targets from derm.fn_blackout_targets(500)
   where ticket_key in ('311780','832487','833049');
  if v_targets = 0 then
    raise exception 'VERIFY: extents written but fn_blackout_targets still returns 0 for these folders - the gate did not open, so something else is blocking';
  end if;

  -- the detector must now show ONLY the two scanned sheets we deliberately did not template
  select count(*) into v_still_blocked from derm.v_blackout_blocked_sheets;
  if v_still_blocked <> 2 then
    raise exception 'VERIFY: expected exactly 2 remaining blocked sheets (ticket-832996, window5-sheet3), found %', v_still_blocked;
  end if;

  -- and they must be those two, not one of the three we just fixed
  select count(*) into v_wrong_page from derm.v_blackout_blocked_sheets
   where dump_folder not in ('ticket-832996','window5-sheet3');
  if v_wrong_page <> 0 then
    raise exception 'VERIFY: a folder we intended to fix is still blocked';
  end if;

  raise notice 'VERIFY ok: 6 extents, % blackout targets now available, 2 scanned sheets deliberately left for a real measurement', v_targets;
end $verify$;

commit;
