-- Add derm_manifests.fog_manifest_url — the per-client generated "FOG Manifest"
-- (a DERM Address rendered with ONLY this manifest row's own client facility in
-- Section B). Shown on the Field Portal workorder in place of the intentionally
-- hidden multi-client derm_address_url. Generated by unclogme-pdf-service
-- (/generate/fog-manifest) + a one-time backfill.
--
-- AUDIT (rule 8): derm_manifests is already audited; a column ADD is captured
-- automatically in the full-row JSONB by the existing trigger — no trigger change.
ALTER TABLE public.derm_manifests ADD COLUMN IF NOT EXISTS fog_manifest_url text;
