-- 2026-07-16 · public.vehicle_decals — hauler decals are PER (vehicle, jurisdiction)
-- ---------------------------------------------------------------------------
-- Fred supplied the Broward decals (Moises 07675, David 07058). The trucks already
-- carried a Miami-Dade decal in public.vehicles.decal_number (Moises C1184, David C0976).
-- Confirmed by the physical receipts: Miami-Dade SDWWTP prints "Decal No. C1184"
-- (tickets 444849/444980/445331/829788 = Moises); Broward EPD prints "EPD Decal 07675"
-- (ticket 308792 = Moises). The two counties issue separate decals per truck.
--
-- 3NF standing check (Rule 2), per column:
--   vehicle_id    - part of the key.
--   jurisdiction  - part of the key (a truck has ONE decal per county).
--   decal_number  - depends on the WHOLE key (vehicle_id, jurisdiction) and nothing else. ✔
--   status/notes  - depend on the whole key. ✔
-- A `decal_number_broward` column was REJECTED: it is a repeating group (a third county
-- would need a third column) and it breaks the 3NF standing check. Same spirit as Rule 1:
-- no jurisdiction-prefixed columns on a business table.
--
-- Audit standing check (Rule 8): human-editable business data -> OPT-IN. audit_vehicle_decals
-- added (AFTER INSERT/UPDATE/DELETE -> audit.log_change()). public.vehicles is already audited.
--
-- Security: mirrors public.vehicles exactly (RLS enabled + FORCED; anon/authenticated SELECT
-- only; service_role writes). Does not widen the 2026-07-12 anon read-only posture.
--
-- NOTE: public.vehicles.decal_number is LEFT IN PLACE (legacy Miami-Dade value). It is still
-- read by ops.vehicles + ops.v_calendar_truck, which are VEHICLE-level surfaces where a
-- per-load disposal county does not apply. customer.work_orders.decal was re-pointed, see
-- ADDENDUM below. Treat vehicles.decal_number as the legacy Dade-only field.

CREATE TABLE IF NOT EXISTS public.vehicle_decals (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id    bigint NOT NULL REFERENCES public.vehicles(id) ON DELETE RESTRICT,
  jurisdiction  text   NOT NULL,
  decal_number  text   NOT NULL,
  status        text   NOT NULL DEFAULT 'ACTIVE',
  notes         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT vehicle_decals_jurisdiction_chk CHECK (jurisdiction IN ('Miami-Dade','Broward','Palm Beach')),
  CONSTRAINT vehicle_decals_status_chk CHECK (status IN ('ACTIVE','INACTIVE')),
  CONSTRAINT vehicle_decals_vehicle_jurisdiction_uniq UNIQUE (vehicle_id, jurisdiction)
);

DROP TRIGGER IF EXISTS trg_vehicle_decals_updated_at ON public.vehicle_decals;
CREATE TRIGGER trg_vehicle_decals_updated_at BEFORE UPDATE ON public.vehicle_decals
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();   -- Rule 7: never set updated_at by hand

DROP TRIGGER IF EXISTS audit_vehicle_decals ON public.vehicle_decals;
CREATE TRIGGER audit_vehicle_decals AFTER INSERT OR UPDATE OR DELETE ON public.vehicle_decals
  FOR EACH ROW EXECUTE FUNCTION audit.log_change();        -- Rule 8: opt-in

ALTER TABLE public.vehicle_decals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_decals FORCE ROW LEVEL SECURITY;
REVOKE ALL ON public.vehicle_decals FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.vehicle_decals TO anon, authenticated, yannick_readonly;
GRANT ALL    ON public.vehicle_decals TO service_role;
DROP POLICY IF EXISTS vehicle_decals_service_role_all ON public.vehicle_decals;
CREATE POLICY vehicle_decals_service_role_all ON public.vehicle_decals FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS vehicle_decals_anon_read ON public.vehicle_decals;
CREATE POLICY vehicle_decals_anon_read ON public.vehicle_decals FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS vehicle_decals_authn_read ON public.vehicle_decals;
CREATE POLICY vehicle_decals_authn_read ON public.vehicle_decals FOR SELECT TO authenticated USING (true);

-- Migrate the existing Miami-Dade decals off vehicles.decal_number (idempotent, Rule 5).
INSERT INTO public.vehicle_decals (vehicle_id, jurisdiction, decal_number)
SELECT v.id, 'Miami-Dade', btrim(v.decal_number)
FROM   public.vehicles v
WHERE  v.decal_number IS NOT NULL AND btrim(v.decal_number) <> ''
ON CONFLICT (vehicle_id, jurisdiction) DO NOTHING;

-- Broward decals (Fred 2026-07-16). Idempotent on the natural key.
INSERT INTO public.vehicle_decals (vehicle_id, jurisdiction, decal_number)
SELECT veh.id, 'Broward', x.decal
FROM  (VALUES ('Moises','07675'), ('David','07058')) AS x(nm, decal)
JOIN   public.vehicles veh ON veh.name = x.nm
ON CONFLICT (vehicle_id, jurisdiction) DO UPDATE SET decal_number = EXCLUDED.decal_number;

-- Applied to Prod 2026-07-16. Verified: 4 rows (Moises Miami-Dade C1184 / Broward 07675;
-- David Miami-Dade C0976 / Broward 07058); grants identical to public.vehicles; RLS enabled
-- + forced; audit.logs captured 4 INSERTs with app_source='sql-vehicle-decals-broward'.
-- Cloggy and Goliath have no decal on record in either county.


-- ============================================================================
-- ADDENDUM 2026-07-16 - customer.work_orders.decal -> the DISPOSAL FACILITY's county
-- ============================================================================
-- Fred's decision: the decal shown on a customer work order is the decal for the county of
-- the facility where THAT LOAD ACTUALLY WENT, not the client's county. The two differ: the
-- Broward receipt (ticket 308792) literally reads "Service Area: Dade County" + "Mix Load",
-- i.e. Dade-collected grease dumped at Broward.
--
-- Chain: visit -> manifest_visits -> derm_manifests -> disposal_facilities.county
--        -> vehicle_decals (vehicle_id = the visit's truck, jurisdiction = that county).
--
-- If the visit has no linked manifest we do not know where the load went, so decal is NULL
-- rather than guessing the Dade decal. That is deliberate and matches the Field Portal rule
-- of not showing a customer something we cannot stand behind.
--
-- Applied via CREATE OR REPLACE grafted onto the LIVE definition. Verified by diffing the live
-- view before/after: the ONLY change is the decal expression (one line removed, the subquery
-- added); every other line is byte-identical, so Supabase 1's services COALESCE fallback and
-- the derm redaction joins (rd.url / receipt_doc_class) are preserved verbatim.
-- Backup of the previous definition: backups/2026-07-16_customer_work_orders_before_decal.sql
--
-- Verified after: work_orders 545 rows (unchanged); services 545, FOG 519, WWTP 517, truck 525,
-- driver 543 (all unchanged); grants preserved (anon/authenticated SELECT).
-- Decal distribution now: C1184 Moises 297 + C0976 David 114 (Dade loads);
-- 07675 Moises 60 + 07058 David 31 (Broward loads - these 91 previously showed the WRONG
-- Miami-Dade decal); none: Cloggy 17 (no decals on record for Cloggy) + 6 visits with no
-- linked manifest.

/*  Grafted expression (replaces `veh.decal_number AS decal`):

    ( SELECT vd.decal_number
        FROM public.manifest_visits mv
          JOIN public.derm_manifests dm ON dm.id = mv.manifest_id AND dm.deleted_at IS NULL
          JOIN public.disposal_facilities df ON df.id = dm.disposal_facility_id
          JOIN public.vehicle_decals vd ON vd.vehicle_id = veh.id
                                       AND vd.jurisdiction = df.county
                                       AND vd.status = 'ACTIVE'
       WHERE mv.visit_id = v.id
       LIMIT 1) AS decal
*/

-- OPEN: Cloggy has no decal on record in either county (17 work orders show none), and
-- Goliath (INACTIVE) has none either. Supply them and they resolve with no code change.
