-- ============================================================================================
-- 2026-09-15_1100_template_rules_precedence.sql   (GENERATED by
-- scripts/probes/generated_finisher/gen_precedence_migration.py from the live bodies; do not edit
-- the view bodies by hand, re-run the generator)
--
-- A third rule source, `template-v1-<date>`: printed lines matched to the layout of a GENERATED sheet
-- by the finisher (derm.fn_generated_page_measured, migration 2026-09-15_1200). Precedence per page:
--     human-v1  (a person marked the lines)            rank 0
--     template-v1 (layout-guided match on a sheet we printed)  rank 1
--     runlen-v2 (the blind detector + classifier)      rank 2
-- A person's lines always win. The layout-guided set outranks the blind classifier's on the same
-- page: when the blind scan graded OK the two are the same six lines anyway, and when it did not
-- (835076 page 2, a half-width boundary) the layout-guided set is the one that is right.
--
-- ONE PREDICATE, ONE RANK, TWO READERS. derm._is_rule_source() already existed (writer side, in
-- record_page_rules); derm._rule_source_rank() is new. Both readers that select a scan are
-- re-pointed at them: derm.v_page_printed_rules AND derm.v_band_edge_check, whose own copy of the
-- selection CTE was missed once already (2026-09-07_1810). record_page_rules' refusal text names
-- the third prefix.
--
-- INERT AT INSTALL: no template-v1 scan exists yet, so both views serve byte-identical rows before
-- and after (VERIFY 1). The precedence is proven on a synthetic scan inside a savepoint (VERIFY 2).
--
-- BODY PROVENANCE: pg_get_viewdef / pg_get_functiondef output patched by anchored replacement, each
-- anchor asserted to occur exactly once by the generator.
-- RULE 8: no table changes, views and functions only.
-- ============================================================================================
BEGIN;

CREATE TEMP TABLE _vppr_before ON COMMIT DROP AS SELECT * FROM derm.v_page_printed_rules;
CREATE TEMP TABLE _vbec_before ON COMMIT DROP AS
  SELECT dump_folder, effective_page, row_id, edge_verdict, slot_verdict FROM derm.v_band_edge_check;

CREATE OR REPLACE FUNCTION derm._rule_source_rank(p_source text)
RETURNS integer
LANGUAGE sql IMMUTABLE
AS $function$
  -- lower wins. NULL for a source no reader admits.
  SELECT CASE
           WHEN p_source LIKE 'human-v1-%'    THEN 0
           WHEN p_source LIKE 'template-v1-%' THEN 1
           WHEN p_source LIKE 'runlen-v2-%'   THEN 2
         END;
$function$;

CREATE OR REPLACE FUNCTION derm._is_rule_source(p_source text)
RETURNS boolean
LANGUAGE sql IMMUTABLE
AS $function$
  SELECT p_source IS NOT NULL
     AND (p_source LIKE 'runlen-v2-%' OR p_source LIKE 'human-v1-%' OR p_source LIKE 'template-v1-%');
$function$;

CREATE OR REPLACE VIEW derm.v_page_printed_rules AS
 WITH scan AS (
         SELECT DISTINCT ON (s.dump_folder, s.effective_page) s.dump_folder,
            s.effective_page,
            s.source,
            s.scanned_at,
            s.grade,
            s.source_etag,
            s.source_url
           FROM derm.page_rule_scans s
          WHERE derm._is_rule_source(s.source)
          ORDER BY s.dump_folder, s.effective_page, derm._rule_source_rank(s.source), s.scanned_at DESC
        )
 SELECT sc.dump_folder,
    sc.effective_page,
    pr.rule_pct,
    pr.kind,
    pr.kind_confirmed,
    pr.run_frac,
    pr.ink_frac,
    sc.source,
    sc.scanned_at,
    sc.grade,
    sc.source_etag,
    sc.source_url
   FROM scan sc
     JOIN derm.page_row_rules pr ON pr.dump_folder = sc.dump_folder AND pr.effective_page = sc.effective_page AND pr.source = sc.source;

CREATE OR REPLACE VIEW derm.v_band_edge_check AS
 WITH served AS (
         SELECT r.id AS row_id,
            r.dump_folder,
            COALESCE(r.stamp_page, r.page) AS effective_page,
            c.client_code,
            vb.band_y0_pct,
            vb.band_y1_pct,
            r.band_source,
            r.stamp_y_pct,
            r.band_y0_pct IS NOT NULL AS band_is_override,
            d.band_y0 = grp.u0 AND d.band_y1 = grp.u1 AS doc_current,
            d.source_url AS doc_source_url,
            d.url AS doc_url
           FROM derm.address_row_map r
             JOIN clients c ON c.id = r.matched_client_id
             JOIN derm.v_stamp_row_bands vb ON vb.id = r.id
             JOIN derm.redacted_manifest_docs d ON d.manifest_id = r.matched_manifest_id AND d.client_id = r.matched_client_id AND d.effective_page = COALESCE(r.stamp_page, r.page)
             CROSS JOIN LATERAL ( SELECT min(b2.band_y0_pct) AS u0,
                    max(b2.band_y1_pct) AS u1
                   FROM derm.address_row_map r2
                     JOIN derm.v_stamp_row_bands b2 ON b2.id = r2.id
                  WHERE r2.matched_manifest_id = r.matched_manifest_id AND r2.matched_client_id = r.matched_client_id AND r2.dump_folder = r.dump_folder AND COALESCE(r2.stamp_page, r2.page) = COALESCE(r.stamp_page, r.page) AND r2.stamp_placed_at IS NOT NULL) grp
          WHERE d.band_y0 IS NOT NULL AND d.band_y1 IS NOT NULL
        ), scan AS (
         SELECT DISTINCT ON (page_rule_scans.dump_folder, page_rule_scans.effective_page) page_rule_scans.dump_folder,
            page_rule_scans.effective_page,
            page_rule_scans.source_url,
            page_rule_scans.image_w,
            page_rule_scans.image_h,
            page_rule_scans.skew,
            page_rule_scans.n_rules,
            page_rule_scans.n_boundaries,
            page_rule_scans.pitch_pct,
            page_rule_scans.grade,
            page_rule_scans.detail,
            page_rule_scans.source,
            page_rule_scans.scanned_at,
            page_rule_scans.source_etag,
            page_rule_scans.skew_saturated
           FROM derm.page_rule_scans
          WHERE derm._is_rule_source(page_rule_scans.source)
          ORDER BY page_rule_scans.dump_folder, page_rule_scans.effective_page, derm._rule_source_rank(page_rule_scans.source), page_rule_scans.scanned_at DESC
        ), m AS (
         SELECT s.row_id,
            s.dump_folder,
            s.effective_page,
            s.client_code,
            s.band_y0_pct,
            s.band_y1_pct,
            s.band_source,
            s.stamp_y_pct,
            s.band_is_override,
            s.doc_current,
            s.doc_source_url,
            s.doc_url,
            GREATEST(COALESCE(( SELECT count(*) AS count
                   FROM derm.address_row_map a2
                     JOIN derm_manifests dm ON dm.id = a2.matched_manifest_id AND dm.deleted_at IS NULL
                     JOIN derm.address_sheet_manifests asm ON asm.manifest_id = dm.id
                     JOIN derm.address_sheets ash ON ash.id = asm.sheet_id AND ash.deleted_at IS NULL
                     JOIN derm.v_sheet_printed_rows vpr ON vpr.sheet_id = asm.sheet_id AND vpr.client_id = a2.matched_client_id
                  WHERE a2.id = s.row_id AND derm.fn_sheet_image_position(a2.dump_folder, vpr.printed_page) = s.effective_page), 0::bigint) / GREATEST(COALESCE(( SELECT count(*) AS count
                   FROM derm.address_row_map a3
                  WHERE a3.dump_folder = s.dump_folder AND a3.matched_client_id = (( SELECT a4.matched_client_id
                           FROM derm.address_row_map a4
                          WHERE a4.id = s.row_id)) AND COALESCE(a3.stamp_page, a3.page) = s.effective_page), 1::bigint), 1::bigint), 1::bigint)::integer AS expected_slots,
            sc.grade AS page_grade,
            sc.n_rules,
            sc.pitch_pct,
            sc.source_etag,
            sc.skew_saturated,
            sc.dump_folder AS scanned,
            t.d AS top_gap_pct,
            t.kind AS top_kind,
            b.d AS bottom_gap_pct,
            b.kind AS bottom_kind,
            ib.n AS inner_boundaries,
            idv.n AS inner_dividers,
            COALESCE(( SELECT count(*) AS count
                   FROM derm.page_row_rules pr
                  WHERE pr.dump_folder = s.dump_folder AND pr.effective_page = s.effective_page AND pr.source = sc.source AND pr.kind = 'divider'::text), 0::bigint) AS page_dividers
           FROM served s
             LEFT JOIN scan sc ON sc.dump_folder = s.dump_folder AND sc.effective_page = s.effective_page
             LEFT JOIN LATERAL ( SELECT abs(pr.rule_pct - s.band_y0_pct) AS d,
                    pr.kind
                   FROM derm.page_row_rules pr
                  WHERE pr.dump_folder = s.dump_folder AND pr.effective_page = s.effective_page AND pr.source = sc.source
                  ORDER BY (abs(pr.rule_pct - s.band_y0_pct))
                 LIMIT 1) t ON true
             LEFT JOIN LATERAL ( SELECT abs(pr.rule_pct - s.band_y1_pct) AS d,
                    pr.kind
                   FROM derm.page_row_rules pr
                  WHERE pr.dump_folder = s.dump_folder AND pr.effective_page = s.effective_page AND pr.source = sc.source
                  ORDER BY (abs(pr.rule_pct - s.band_y1_pct))
                 LIMIT 1) b ON true
             LEFT JOIN LATERAL ( SELECT count(*) AS n
                   FROM derm.page_row_rules pr
                  WHERE pr.dump_folder = s.dump_folder AND pr.effective_page = s.effective_page AND pr.source = sc.source AND pr.kind = 'boundary'::text AND pr.rule_pct > (s.band_y0_pct + 0.35) AND pr.rule_pct < (s.band_y1_pct - 0.35)) ib ON true
             LEFT JOIN LATERAL ( SELECT count(*) AS n
                   FROM derm.page_row_rules pr
                  WHERE pr.dump_folder = s.dump_folder AND pr.effective_page = s.effective_page AND pr.source = sc.source AND pr.kind = 'divider'::text AND pr.rule_pct > (s.band_y0_pct + 0.35) AND pr.rule_pct < (s.band_y1_pct - 0.35)) idv ON true
        )
 SELECT row_id,
    dump_folder,
    effective_page,
    client_code,
    doc_url,
    band_y0_pct,
    band_y1_pct,
    band_source,
    band_is_override,
    doc_current,
    page_grade,
    n_rules,
    pitch_pct,
    skew_saturated,
    top_gap_pct,
    top_kind,
    bottom_gap_pct,
    bottom_kind,
    inner_boundaries,
    inner_dividers,
    expected_slots,
        CASE
            WHEN scanned IS NULL THEN 'UNSCANNED'::text
            WHEN source_etag IS DISTINCT FROM derm._img_etag(doc_source_url) THEN 'STALE'::text
            WHEN top_gap_pct IS NULL OR bottom_gap_pct IS NULL THEN 'OFF_RULE'::text
            WHEN top_gap_pct <= 0.35 AND bottom_gap_pct <= 0.35 THEN 'ON_RULE'::text
            ELSE 'OFF_RULE'::text
        END AS edge_verdict,
        CASE
            WHEN scanned IS NULL OR page_grade = 'FAILED'::text OR top_kind = 'unclassified'::text OR bottom_kind = 'unclassified'::text OR top_kind IS NULL OR bottom_kind IS NULL THEN 'UNKNOWN'::text
            WHEN top_kind = 'boundary'::text AND bottom_kind = 'boundary'::text AND inner_boundaries = (expected_slots - 1) AND (inner_dividers = expected_slots OR page_dividers = 0) THEN 'ONE_CLIENT'::text
            WHEN inner_boundaries > (expected_slots - 1) THEN 'SPANS_MULTIPLE'::text
            WHEN top_kind = 'boundary'::text AND bottom_kind = 'boundary'::text THEN 'ODD_SLOT'::text
            ELSE 'PART_SLOT'::text
        END AS slot_verdict
   FROM m;

CREATE OR REPLACE FUNCTION derm.record_page_rules(p_dump_folder text, p_effective_page integer, p_source text, p_source_url text, p_rules jsonb, p_meta jsonb DEFAULT '{}'::jsonb, p_force boolean DEFAULT false)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'derm', 'public', 'pg_temp'
AS $function$
DECLARE
  v_grade      text := coalesce(p_meta->>'grade', 'FAILED');
  v_detail     text := p_meta->>'detail';
  -- 🛑 COMPUTE THE ETAG WHEN THE CALLER OMITS IT. A NULL here makes every band on the page read
  -- STALE in v_band_edge_check, because that check compares the etag BEFORE it compares any edge
  -- and NULL is DISTINCT FROM everything. The app does not send one; this is why it must not matter.
  v_etag       text := coalesce(p_meta->>'source_etag', derm._img_etag(p_source_url));
  v_reject     text;
  v_prev       record;
  v_n_rules    integer := 0;
  v_n_bounds   integer := 0;
  v_pitch      numeric;
  v_wrote      boolean := false;
  v_hint       text;
BEGIN
  -- 2026-09-02: 'human-v1-%' admitted alongside 'runlen-v2-%'. The READER was widened by
  -- 2026-09-02_0330 and this WRITER was not, so an operator-marked page raised
  -- "source must match runlen-v2-%" and nothing could ever be recorded. Measured before this
  -- migration: 176 scans exist and every one is runlen-v2, i.e. the widened view had never
  -- admitted a single row and was inert from the hour it shipped.
  IF NOT derm._is_rule_source(p_source) THEN
    RAISE EXCEPTION 'source must match runlen-v2-%%, human-v1-%% or template-v1-%%, got %',
      coalesce(p_source,'<null>') USING ERRCODE = '22023';
  END IF;
  IF p_dump_folder IS NULL OR p_effective_page IS NULL THEN
    RAISE EXCEPTION 'dump_folder and effective_page are required' USING ERRCODE = '22023';
  END IF;
  IF v_grade NOT IN ('OK','IRREGULAR','SPARSE','FAILED') THEN
    RAISE EXCEPTION 'grade % is outside the allowed vocabulary', v_grade USING ERRCODE = '22023';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM derm.address_row_map r
                  WHERE r.dump_folder = p_dump_folder
                    AND coalesce(r.stamp_page, r.page) = p_effective_page) THEN
    RAISE EXCEPTION 'no cards on %/% : refusing to record rules for a page that does not exist',
      p_dump_folder, p_effective_page USING ERRCODE = '22023';
  END IF;

  -- 2026-09-02_1520: THE VALIDATOR RUNS BEFORE THE SUPERSESSION GUARD, and the order is the whole
  -- point of this migration. v_grade starts as the grade the CALLER CLAIMED. The guard below
  -- compares that value, so while validation ran AFTER it the guard could only ever see a caller
  -- that SAID 'FAILED'. The detector never does: it claims OK and lets the server judge. So a
  -- re-measure whose rules the validator rejects sailed past the guard, was written as the newest
  -- scan for the page, and v_page_printed_rules -- which joins rules on the newest scan's OWN
  -- source -- then served ZERO rules. The operator's hand-marked geometry vanished from every
  -- reader while still sitting in page_row_rules.
  -- Measured on ticket-834489 before the fix, replaying that page's real rejected detector
  -- payload: rules served went 7 -> 0, and the RPC reported wrote:false as if it had done nothing.
  IF v_grade <> 'FAILED' THEN
    v_reject := derm.fn_validate_page_rules(p_rules);
    IF v_reject IS NOT NULL THEN
      v_grade  := 'FAILED';
      v_detail := 'rejected by fn_validate_page_rules: ' || v_reject;
      -- the stored detail keeps the validator's exact words, because page_rule_scans.detail
      -- is the forensic record. The OPERATOR gets the plain sentence, returned separately.
      v_hint   := derm.fn_rule_hint(v_reject);
    END IF;
  END IF;
  SELECT s.grade, s.source, s.source_etag, s.scanned_at
    INTO v_prev
    FROM derm.page_rule_scans s
   WHERE s.dump_folder = p_dump_folder AND s.effective_page = p_effective_page
     AND derm._is_rule_source(s.source)
   ORDER BY s.scanned_at DESC
   LIMIT 1;

  -- 2026-09-02: was v_prev.grade = 'OK'. Widened to any non-FAILED grade because rules are
  -- WRITTEN on OK, SPARSE and IRREGULAR alike, and the view joins rules on the NEWEST scan's
  -- own source. So a later FAILED scan does not delete the old rules, it HIDES them: the page
  -- silently serves zero rules and every band on it grades UNSCANNED. Live corpus: 8 SPARSE
  -- and 2 IRREGULAR scans were exposed to that, and 0 pages are shadowed today, so this
  -- changes no existing row and is purely protective.
  IF FOUND AND v_prev.grade <> 'FAILED' AND v_grade = 'FAILED' AND NOT p_force
     AND (v_etag IS NULL OR v_prev.source_etag IS NULL OR v_etag = v_prev.source_etag) THEN
    RETURN jsonb_build_object(
      'wrote', false, 'grade', v_grade, 'rules_written', 0,
      'skipped', 'would_supersede_ok',
      -- 2026-09-02: the article is chosen from the grade rather than hardcoded 'a'. The grade
      -- vocabulary is OK / IRREGULAR / SPARSE / FAILED, so two of the four take 'an' and the
      -- message read "already has a OK scan" on the commonest one.
      'detail', format('this page already has %s %s scan (%s) and the image has not changed; '
                       || 'refusing to replace it with a %s result',
                       CASE WHEN left(v_prev.grade, 1) IN ('A','E','I','O','U')
                            THEN 'an' ELSE 'a' END,
                       v_prev.grade, v_prev.source, v_grade));
  END IF;


  SELECT count(*), count(*) FILTER (WHERE e->>'kind' = 'boundary')
    INTO v_n_rules, v_n_bounds
    FROM jsonb_array_elements(coalesce(p_rules,'[]'::jsonb)) e;

  IF v_grade <> 'FAILED' THEN
    WITH b AS (
      SELECT (e->>'pct')::numeric AS pct
        FROM jsonb_array_elements(p_rules) e
       WHERE e->>'kind' = 'boundary'
       ORDER BY 1
    ), g AS (
      SELECT pct - lag(pct) OVER (ORDER BY pct) AS gap FROM b
    )
    SELECT percentile_disc(0.5) WITHIN GROUP (ORDER BY gap) INTO v_pitch FROM g WHERE gap IS NOT NULL;
  END IF;

  INSERT INTO derm.page_rule_scans
    (dump_folder, effective_page, source_url, image_w, image_h, skew,
     n_rules, n_boundaries, pitch_pct, grade, detail, source, scanned_at, source_etag, skew_saturated)
  VALUES
    (p_dump_folder, p_effective_page, coalesce(p_source_url,'(unknown)'),
     (p_meta->>'image_w')::int, (p_meta->>'image_h')::int, (p_meta->>'skew')::numeric,
     v_n_rules, v_n_bounds, v_pitch, v_grade, v_detail, p_source, now(), v_etag,
     coalesce((p_meta->>'skew_saturated')::boolean, false))
  ON CONFLICT (dump_folder, effective_page, source) DO UPDATE
    SET source_url = EXCLUDED.source_url, image_w = EXCLUDED.image_w, image_h = EXCLUDED.image_h,
        skew = EXCLUDED.skew, n_rules = EXCLUDED.n_rules, n_boundaries = EXCLUDED.n_boundaries,
        pitch_pct = EXCLUDED.pitch_pct, grade = EXCLUDED.grade, detail = EXCLUDED.detail,
        scanned_at = EXCLUDED.scanned_at, source_etag = EXCLUDED.source_etag,
        skew_saturated = EXCLUDED.skew_saturated;

  IF v_grade <> 'FAILED' THEN
    DELETE FROM derm.page_row_rules
     WHERE dump_folder = p_dump_folder AND effective_page = p_effective_page AND source = p_source;
    INSERT INTO derm.page_row_rules
      (dump_folder, effective_page, rule_pct, ink_frac, source, detected_at, run_frac, kind, kind_confirmed)
    SELECT p_dump_folder, p_effective_page,
           (e->>'pct')::numeric, coalesce((e->>'ink')::numeric, 0), p_source, now(),
           (e->>'run')::numeric, e->>'kind', false
      FROM jsonb_array_elements(p_rules) e;
    v_wrote := true;
  END IF;

  RETURN jsonb_build_object(
    'wrote', v_wrote, 'grade', v_grade,
    'rules_written', CASE WHEN v_wrote THEN v_n_rules ELSE 0 END,
    'n_boundaries', v_n_bounds, 'pitch', v_pitch, 'detail', v_detail, 'hint', v_hint,
    'source_etag', v_etag);
END $function$;

-- --------------------------------------------------------------------------------------------
-- VERIFY
-- --------------------------------------------------------------------------------------------
DO $verify$
DECLARE v_n int; v_url text; v_j jsonb; v_on_before int; v_on_after int;
BEGIN
  -- 1. inert at install: both readers serve the same rows as before
  SELECT count(*) INTO v_n FROM (
    (SELECT * FROM derm.v_page_printed_rules EXCEPT SELECT * FROM _vppr_before)
    UNION ALL
    (SELECT * FROM _vppr_before EXCEPT SELECT * FROM derm.v_page_printed_rules)) d;
  IF v_n <> 0 THEN RAISE EXCEPTION 'VERIFY 1a FAILED: v_page_printed_rules moved % rows', v_n; END IF;
  SELECT count(*) INTO v_n FROM (
    (SELECT dump_folder, effective_page, row_id, edge_verdict, slot_verdict FROM derm.v_band_edge_check EXCEPT SELECT * FROM _vbec_before)
    UNION ALL
    (SELECT * FROM _vbec_before EXCEPT SELECT dump_folder, effective_page, row_id, edge_verdict, slot_verdict FROM derm.v_band_edge_check)) d;
  IF v_n <> 0 THEN RAISE EXCEPTION 'VERIFY 1b FAILED: v_band_edge_check moved % rows', v_n; END IF;

  -- 1c. the rank and the predicate
  IF derm._rule_source_rank('human-v1-x') <> 0 OR derm._rule_source_rank('template-v1-x') <> 1
     OR derm._rule_source_rank('runlen-v2-x') <> 2 OR derm._rule_source_rank('claude-fix') IS NOT NULL
     OR NOT derm._is_rule_source('template-v1-2026-09-15') OR derm._is_rule_source('template-v2-x') OR derm._is_rule_source(NULL) THEN
    RAISE EXCEPTION 'VERIFY 1c FAILED: rank or predicate';
  END IF;

  -- 2. precedence, on a real page inside a savepoint. ticket-310429 p1: one runlen-v2 scan, no human
  --    scan, serving documents (so v_band_edge_check grades it).
  IF EXISTS (SELECT 1 FROM derm.page_rule_scans WHERE dump_folder = 'ticket-310429' AND effective_page = 1 AND source NOT LIKE 'runlen-v2-%') THEN
    RAISE EXCEPTION 'VERIFY 2 SETUP: ticket-310429 p1 is no longer a runlen-only page; pick another fixture';
  END IF;
  SELECT count(*) INTO v_on_before FROM derm.v_band_edge_check WHERE dump_folder = 'ticket-310429' AND effective_page = 1 AND edge_verdict = 'ON_RULE';
  IF v_on_before = 0 THEN RAISE EXCEPTION 'VERIFY 2 SETUP: ticket-310429 p1 has no ON_RULE band to move; pick another fixture'; END IF;
  v_url := (derm.ticket_page_images('310429'))[1];
  BEGIN
    -- a template scan OLDER than the runlen one, with six lines nowhere near the real ones
    INSERT INTO derm.page_rule_scans (dump_folder, effective_page, source_url, n_rules, n_boundaries, grade, source, scanned_at, source_etag)
    VALUES ('ticket-310429', 1, v_url, 6, 6, 'OK', 'template-v1-verify', '2020-01-01', derm._img_etag(v_url));
    INSERT INTO derm.page_row_rules (dump_folder, effective_page, rule_pct, ink_frac, source, run_frac, kind, kind_confirmed)
    SELECT 'ticket-310429', 1, p, 0.9, 'template-v1-verify', 0.99, 'boundary', false FROM unnest(ARRAY[10,20,30,40,50,60]) p;
    IF (SELECT count(*) FROM derm.v_page_printed_rules WHERE dump_folder = 'ticket-310429' AND effective_page = 1 AND source = 'template-v1-verify') <> 6
       OR (SELECT count(*) FROM derm.v_page_printed_rules WHERE dump_folder = 'ticket-310429' AND effective_page = 1 AND source <> 'template-v1-verify') <> 0 THEN
      RAISE EXCEPTION 'VERIFY 2a FAILED: an older template-v1 scan did not outrank the runlen-v2 scan';
    END IF;
    -- the band grader follows: the real bands are now off the (fake) rules, so ON_RULE must drop
    SELECT count(*) INTO v_on_after FROM derm.v_band_edge_check WHERE dump_folder = 'ticket-310429' AND effective_page = 1 AND edge_verdict = 'ON_RULE';
    IF v_on_after >= v_on_before THEN
      RAISE EXCEPTION 'VERIFY 2b FAILED: v_band_edge_check still grades against the runlen scan (ON_RULE % -> %)', v_on_before, v_on_after;
    END IF;
    -- a human scan older still: it wins over the template scan
    INSERT INTO derm.page_rule_scans (dump_folder, effective_page, source_url, n_rules, n_boundaries, grade, source, scanned_at, source_etag)
    VALUES ('ticket-310429', 1, v_url, 7, 7, 'OK', 'human-v1-verify', '2019-01-01', derm._img_etag(v_url));
    INSERT INTO derm.page_row_rules (dump_folder, effective_page, rule_pct, ink_frac, source, run_frac, kind, kind_confirmed)
    SELECT 'ticket-310429', 1, p, 0.9, 'human-v1-verify', 0.99, 'boundary', false FROM unnest(ARRAY[11,21,31,41,51,61,71]) p;
    IF (SELECT count(*) FROM derm.v_page_printed_rules WHERE dump_folder = 'ticket-310429' AND effective_page = 1 AND source = 'human-v1-verify') <> 7 THEN
      RAISE EXCEPTION 'VERIFY 2c FAILED: a human scan did not outrank the template scan';
    END IF;
    -- 2d. record_page_rules accepts the new prefix and refuses an unknown one with the new words
    v_j := derm.record_page_rules('ticket-310429', 1, 'template-v1-verify2', v_url,
             (SELECT jsonb_agg(jsonb_build_object('pct', p, 'run', 0.99, 'kind', 'boundary')) FROM unnest(derm.fn_generated_template_boundaries()) p),
             '{"grade":"OK","detail":"verify"}'::jsonb);
    IF NOT coalesce((v_j->>'wrote')::boolean, false) THEN RAISE EXCEPTION 'VERIFY 2d FAILED: %', v_j; END IF;
    BEGIN
      PERFORM derm.record_page_rules('ticket-310429', 1, 'bogus-v1-x', v_url, '[]'::jsonb, '{}'::jsonb);
      RAISE EXCEPTION 'VERIFY 2e FAILED: an unknown source was accepted';
    EXCEPTION WHEN OTHERS THEN
      IF SQLERRM LIKE 'VERIFY 2e%' THEN RAISE; END IF;
      IF SQLERRM NOT LIKE 'source must match runlen-v2-%, human-v1-% or template-v1-%' THEN
        RAISE EXCEPTION 'VERIFY 2e FAILED: message is "%"', SQLERRM;
      END IF;
    END;
    RAISE EXCEPTION 'RB';   -- roll the fixture back
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'RB' THEN RAISE; END IF;
  END;
  IF EXISTS (SELECT 1 FROM derm.page_rule_scans WHERE source LIKE '%-verify%') THEN
    RAISE EXCEPTION 'VERIFY 2 CLEANUP FAILED: fixture scans survived the rollback';
  END IF;

  RAISE NOTICE 'ALL VERIFY PASSED: inert at install; template-v1 outranks runlen-v2 and is outranked by human-v1 in BOTH readers; record_page_rules admits the prefix.';
END
$verify$;

COMMIT;
