-- ============================================================================
-- 2026-08-10_1415: drop the legacy access trio (STAGED -- NOT YET APPLIED)
-- ============================================================================
-- Step 4, the last one. Fred, 2026-08-10: "once that is complete we can drop the
-- old way."
--
-- 🛑 THIS FILE IS DESTRUCTIVE AND NEEDS FRED'S EXPLICIT GO BEFORE IT IS APPLIED.
-- CLAUDE.md: "Ask before destructive ops. DROP, DELETE, git reset --hard,
-- git push --force -> explicit confirmation." His sentence authorised the PLAN and
-- was conditional on the checks he had not yet seen. It is dry-run verified below
-- and applying it is a single command; it simply is not mine to run unasked.
--
-- WHY THE RPC CHANGE AND THE DROP ARE ONE MIGRATION AND NOT TWO.
-- Split them and you get one of two broken intermediate states:
--   - RPC first: it stops writing the trio, so the columns silently go stale while
--     still existing. Harmless in effect (nothing reads them since _1330) but it
--     destroys the stored==derived invariant that every check here relies on.
--   - DROP first: the RPC names the columns and raises on every property save.
-- So they land together.
--
-- WHAT IS ALREADY TRUE, MEASURED, BEFORE THIS RUNS
--   views naming the base columns .............. 0   (was 5, until _1330)
--   pg_depend rows on the three columns ........ 0   (control: 5 on access_schedule)
--   PostgREST reads of them off the base table . 0   (every read is ops.v_calendar_visit)
--   authenticated UPDATE on them ............... false (only manhole/sample_port)
--   indexes / constraints / defaults on them ... none
--   stored == derived ......................... 198/198 start, 198/198 end, 198/198 days
--   Calendar, live, signed in ................. 1,512 rows, overnight windows intact
--   Client App, live, signed in ............... 31 keys, 198 hours, 198 day arrays
--
-- THE TWO REMAINING CONSUMERS, BOTH HANDLED HERE
-- 1. client.update_property_operational NAMES the columns and writes them. PART 1
--    removes those three assignments. Body copied from pg_get_functiondef with two
--    anchors each asserted to match exactly once -- NOT retyped. CLAUDE.md's
--    CREATE OR REPLACE rule exists because a retype silently deletes whatever you
--    fail to reproduce, and that cost this repo 3.5 hours of a raising resolver on
--    2026-08-06.
-- 2. client.create_property returns to_jsonb(v_row) over public.properties, so its
--    response quietly goes from 27 keys to 24. Nothing needs changing: a NEW property
--    has no access hours, so the three keys were always null there. Asserted in PART 3.
--
-- 🛑 THE ACCEPTED-KEY ALLOWLIST IS DELIBERATELY NOT TOUCHED.
-- 'access_hours_start', 'access_hours_end' and 'access_days' STAY in the RPC's list of
-- accepted patch keys. Removing a key does not make the RPC ignore it -- it makes the
-- RPC REFUSE THE WHOLE PATCH, so every property save from any cached bundle would fail.
-- They are accept-and-ignore from here on. (See memory:
-- reference_rpc_allowlist_removal_refuses_whole_patch.)
--
-- ...and a legacy-ONLY patch (the keys WITHOUT access_schedule) now RAISES 22023
-- instead of being ignored. Ignoring it would tell the user "saved" while discarding
-- the edit, which is the worst of the three options. Only reachable from a tab cached
-- from before access_schedule shipped on 2026-07-30; the live Client App sends all
-- four keys together, verified in the published bundle.
--
-- REVERSIBILITY. The columns can be re-added and repopulated from access_schedule at
-- any time -- that is exactly what public.fn_sched_open/_close/_days do, and
-- stored==derived was proven on all 198 rows before the drop. No information is lost,
-- only a duplicate copy of it. The 861-row table is also in the hourly Client App
-- Mirror, and refresh_client_mirror.js handles a Prod-dropped column by logging it and
-- leaving the mirror column in place (healDrift, line 260) -- verified, not assumed.
--
-- AUDIT-TRAIL STANDING CHECK (rule 8): public.properties keeps its audit trigger.
-- Dropping a column from an audited table needs no trigger change; audit.log_change
-- snapshots the whole row generically, so new rows simply carry three fewer keys.
-- Historical audit.logs rows KEEP the old keys in old_row/new_row, which is correct:
-- an audit trail records what was observed and is not rewritten.
-- ============================================================================

-- ------------------------------------------- PART 1: stop the RPC writing the trio
-- Generated by copying pg_get_functiondef output and applying two anchored edits,
-- each asserted to match exactly once. Every other byte is unchanged.
CREATE OR REPLACE FUNCTION client.update_property_operational(p_property_id bigint, p_patch jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_allowed text[] := array[
    'zone_id','county','access_hours_start','access_hours_end','access_days',
    'access_notes','notes','grease_trap_manhole_count','sample_port_count',
    -- RETIRED 2026-08-07 (Fred: "remove the Default disposal facility, we don't need that").
    -- Deliberately STILL ACCEPTED so a cached bundle that keeps sending the key is not
    -- refused mid-save; it is simply no longer WRITTEN (see the UPDATE list below).
    -- Measured before removing it: 0 of 856 properties ever carried a value.
    'default_disposal_facility_id',
    'access_schedule'  -- NEW 2026-07-30_2103: per-day windows
  ];
  -- The ONLY vocabulary public.properties.access_days uses (verified: 201 rows,
  -- 0 non-conforming). Long names are accepted as ALIASES and normalised down,
  -- so a stale client cannot introduce a second vocabulary.
  v_days     text[] := array['mon','tue','wed','thu','fri','sat','sun'];
  v_bad      text[];
  v_row      public.properties;
  v_in       text[];
  v_norm     text[];
  v_d        text;
  v_sched    jsonb;
  v_k        text;
  v_open     text;
  v_close    text;
begin
  if auth.uid() is null then
    raise exception 'authentication required' using errcode = '28000';
  end if;
  if lower(coalesce(auth.jwt() ->> 'email','')) not like '%@ayache.com'
     and lower(coalesce(auth.jwt() ->> 'email','')) not like '%@unclogme.com' then
    raise exception 'not a staff account' using errcode = '42501';
  end if;
  if p_property_id is null then
    raise exception 'p_property_id is required' using errcode = '22023';
  end if;
  if p_patch is null or jsonb_typeof(p_patch) <> 'object' or p_patch = '{}'::jsonb then
    raise exception 'p_patch must be a non-empty JSON object' using errcode = '22023';
  end if;

  select array_agg(k) into v_bad
  from jsonb_object_keys(p_patch) k
  where k <> all (v_allowed);
  if v_bad is not null then
    raise exception 'unsupported field(s) for properties: %. Wave 1 allows only %. Address fields are Jobber-owned and geofence/lat/long are Samsara-owned; both would be reverted by the inbound sync.',
      v_bad, v_allowed using errcode = '22023';
  end if;

  if p_patch ? 'grease_trap_manhole_count'
     and nullif(p_patch->>'grease_trap_manhole_count','') is null then
    raise exception 'grease_trap_manhole_count cannot be null' using errcode = '22023';
  end if;

  -- ⚠ BUG 1 FIX. Type check first, then VALUE check. The old version stopped at
  -- the type check, which is how ["Monday","Tuesday"] was accepted.
  if p_patch ? 'access_days' then
    if jsonb_typeof(p_patch->'access_days') not in ('array','null') then
      raise exception 'access_days must be a JSON array of day codes (got %)',
        jsonb_typeof(p_patch->'access_days') using errcode = '22023';
    end if;
    if jsonb_typeof(p_patch->'access_days') = 'array' then
      select array_agg(x) into v_in from jsonb_array_elements_text(p_patch->'access_days') x;
      v_norm := array[]::text[];
      foreach v_d in array coalesce(v_in, array[]::text[]) loop
        -- ⚠ A JSON null becomes SQL NULL here, and `NULL <> all(v_days)` evaluates
        -- to NULL rather than true, so the check below would NOT fire and the NULL
        -- would land in the text[]. Caught by the fix's own test run. Reject first.
        if v_d is null then
          raise exception 'access_days cannot contain a null entry' using errcode = '22023';
        end if;
        v_d := lower(btrim(v_d));
        -- accept the long form as an alias, store the canonical short code
        v_d := case v_d
                 when 'monday' then 'mon' when 'tuesday'   then 'tue'
                 when 'wednesday' then 'wed' when 'thursday' then 'thu'
                 when 'friday' then 'fri' when 'saturday'  then 'sat'
                 when 'sunday' then 'sun' else v_d end;
        if v_d <> all (v_days) then
          raise exception 'access_days: % is not a valid day. Use %', v_d, v_days
            using errcode = '22023';
        end if;
        if v_d <> all (v_norm) then v_norm := v_norm || v_d; end if;  -- de-dup
      end loop;
    end if;
  end if;


  -- NEW: access_schedule validation. Object; keys in mon..sun; values
  -- {open:"HH:MM", close:"HH:MM"} 24h. Overnight open>close is legal (into the
  -- next morning), exactly like the legacy single window.
  if p_patch ? 'access_schedule' then
    if jsonb_typeof(p_patch->'access_schedule') = 'null' then
      v_sched := null;
    elsif jsonb_typeof(p_patch->'access_schedule') <> 'object' then
      raise exception 'access_schedule must be an object keyed by day (mon..sun)'
        using errcode = '22023';
    else
      v_sched := p_patch->'access_schedule';
      for v_k in select jsonb_object_keys(v_sched) loop
        if v_k <> all (v_days) then
          raise exception 'access_schedule: % is not a valid day key. Use %', v_k, v_days
            using errcode = '22023';
        end if;
        v_open  := v_sched->v_k->>'open';
        v_close := v_sched->v_k->>'close';
        if v_open is null or v_close is null
           or v_open  !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
           or v_close !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then
          raise exception 'access_schedule.%: open/close must be 24h "HH:MM" strings', v_k
            using errcode = '22023';
        end if;
      end loop;
    end if;
  end if;

  -- A patch that carries the legacy access keys but NO access_schedule can no
  -- longer be honoured: there is nowhere to put it. Silently ignoring it would show
  -- the user "saved" while discarding the edit, so it raises. Only reachable from a
  -- browser tab cached from before access_schedule shipped (2026-07-30); the live
  -- Client App always sends all four keys together (verified in the published bundle).
  if (p_patch ? 'access_hours_start' or p_patch ? 'access_hours_end' or p_patch ? 'access_days')
     and not (p_patch ? 'access_schedule') then
    raise exception 'access hours are now set through access_schedule -- reload the app'
      using errcode = '22023';
  end if;

  update public.properties p set
    zone_id = case when p_patch ? 'zone_id'
                   then nullif(p_patch->>'zone_id','')::bigint else p.zone_id end,
    county = case when p_patch ? 'county'
                  then nullif(nullif(btrim(p_patch->>'county'),''), 'None')
                  else p.county end,
    -- access_hours_start / access_hours_end / access_days were DROPPED by this
    -- migration. The keys remain ACCEPTED above (removing one makes this RPC refuse
    -- the whole patch, breaking every save from a cached bundle) and are now ignored;
    -- access_schedule is the single store. A legacy-ONLY patch is rejected loudly by
    -- the guard above rather than silently discarded.
    access_schedule = case when p_patch ? 'access_schedule' then v_sched
                           else p.access_schedule end,
    access_notes = case when p_patch ? 'access_notes'
                        then nullif(p_patch->>'access_notes','') else p.access_notes end,
    notes = case when p_patch ? 'notes'
                 then nullif(p_patch->>'notes','') else p.notes end,
    grease_trap_manhole_count = case when p_patch ? 'grease_trap_manhole_count'
                                     then (p_patch->>'grease_trap_manhole_count')::integer
                                     else p.grease_trap_manhole_count end,
    sample_port_count = case when p_patch ? 'sample_port_count'
                             then nullif(p_patch->>'sample_port_count','')::integer
                             else p.sample_port_count end
  where p.id = p_property_id
  returning p.* into v_row;

  if not found then
    raise exception 'property % not found', p_property_id using errcode = 'P0002';
  end if;
  return to_jsonb(v_row);
end;
$function$;

-- --------------------------------------------------------- PART 2: the drop itself
-- RESTRICT, not CASCADE. If anything still depends on these columns the drop must
-- FAIL loudly rather than quietly deleting the dependent object. pg_depend says 0
-- (control: 5 on access_schedule), so RESTRICT should succeed -- and if it does not,
-- that is a finding, not an obstacle to route around with CASCADE.
alter table public.properties drop column access_hours_start restrict;
alter table public.properties drop column access_hours_end   restrict;
alter table public.properties drop column access_days        restrict;

-- --------------------------------------------------------- PART 3: verification
do $do$
declare v_n int; v_keys int; v_txt text; v_sched jsonb; v_pid bigint;
begin
  -- (a) the columns are actually gone
  select count(*) into v_n from information_schema.columns
   where table_schema='public' and table_name='properties'
     and column_name in ('access_hours_start','access_hours_end','access_days');
  if v_n <> 0 then raise exception '% legacy columns survived the drop', v_n; end if;
  -- CONTROL: the column the data now lives in must still be there. Without this,
  -- "0 legacy columns" is also what a dropped-the-wrong-thing migration reports.
  select count(*) into v_n from information_schema.columns
   where table_schema='public' and table_name='properties' and column_name='access_schedule';
  if v_n <> 1 then raise exception 'access_schedule is GONE -- the wrong columns were dropped'; end if;

  -- (b) THE POINT: every app-facing view must still serve the same data, now purely
  -- derived. These numbers are the ones measured before the drop.
  select count(*) into v_n from client.properties where access_hours_start is not null;
  if v_n <> 198 then raise exception 'client.properties now serves % hours, expected 198', v_n; end if;
  select count(*) into v_n from client.properties where access_days is not null;
  if v_n <> 198 then raise exception 'client.properties now serves % day arrays, expected 198', v_n; end if;
  select count(*) into v_n from ops.v_calendar_visit where access_hours_start is not null;
  if v_n <> 1512 then raise exception 'ops.v_calendar_visit now serves % rows, expected 1512', v_n; end if;
  select count(*) into v_n from ops.properties where access_hours_start is not null;
  if v_n <> 198 then raise exception 'ops.properties now serves % hours, expected 198', v_n; end if;
  select count(*) into v_n from ops.v_service_due where access_hours_start is not null;
  if v_n = 0 then raise exception 'ops.v_service_due serves zero access hours'; end if;

  -- a specific, known row rather than only counts: 093-KC is overnight 23:00-05:00
  select access_hours_start into v_txt from client.properties
   where access_schedule->'mon'->>'open' = '23:00' and access_schedule->'mon'->>'close' = '05:00' limit 1;
  if v_txt <> '23:00' then raise exception 'an overnight window now derives as %, expected 23:00', v_txt; end if;

  -- (c) the RPC still round-trips a schedule write, EXERCISED rather than read --
  -- PL/pgSQL is not parsed at CREATE time, so "the migration applied" says nothing
  -- about whether the new body runs. Rolled back inside a subtransaction.
  -- The RPC gates on auth.uid() and a staff email, and the Management API carries no
  -- JWT, so the claims are supplied here. Without this the probe dies 28000 and the
  -- function is never actually executed.
  perform set_config('request.jwt.claims',
    '{"sub":"00000000-0000-0000-0000-000000000000","email":"fred@ayache.com","role":"authenticated"}', true);

  select id, access_schedule into v_pid, v_sched from public.properties
   where access_schedule is not null order by id limit 1;
  begin
    perform client.update_property_operational(v_pid,
      jsonb_build_object('access_schedule', jsonb_build_object(
        'mon', jsonb_build_object('open','07:00','close','19:00'))));
    select access_hours_start into v_txt from client.properties where id = v_pid;
    if v_txt <> '07:00' then
      raise exception 'RPC wrote a schedule but the view derives % , expected 07:00', v_txt;
    end if;
    -- and the legacy-only shape must now RAISE rather than silently no-op
    begin
      perform client.update_property_operational(v_pid, jsonb_build_object('access_hours_start','08:00'));
      raise exception 'a legacy-only patch was ACCEPTED -- the guard is not firing';
    exception when sqlstate '22023' then null;  -- expected
    end;
    raise exception 'ROLLBACK_PROBE';
  exception when others then
    if sqlerrm <> 'ROLLBACK_PROBE' then raise; end if;
  end;
  -- restore is implicit: the inner block rolled back
  select access_schedule into v_sched from public.properties where id = v_pid;
  if v_sched is null then raise exception 'the RPC probe did not roll back -- property % was modified', v_pid; end if;

  -- (d) create_property's response shape: 27 keys -> 24, and no access* key but the schedule
  select count(*) into v_keys from jsonb_object_keys(to_jsonb((select p from public.properties p limit 1)));
  if v_keys <> 24 then raise exception 'properties rowtype now has % keys, expected 24', v_keys; end if;

  raise notice 'trio dropped; all five views still serve identical data, derived from access_schedule';
end
$do$;
