# Generates docs/migrations/2026-09-15_1100_template_rules_precedence.sql from the LIVE view and
# function bodies dumped by precedence_defs.out.sql (Task 4 step 1). Every patch is an anchored
# replacement asserted to occur exactly once; nothing is retyped (CLAUDE.md, CREATE OR REPLACE rule).
# USE: python scripts/probes/generated_finisher/gen_precedence_migration.py
import json, os, sys
here = os.path.dirname(os.path.abspath(__file__))
root = os.path.abspath(os.path.join(here, '..', '..', '..'))
defs = {r['k']: r['def'] for r in json.load(open(os.path.join(here, 'precedence_defs.out.json'), encoding='utf-8'))}

def patch(body, pairs, name):
    for old, new in pairs:
        n = body.count(old)
        if n != 1:
            sys.exit(f'{name}: anchor occurs {n} times, expected 1:\n{old}')
        body = body.replace(old, new)
    return body

vppr = patch(defs['v_page_printed_rules'], [
    ("WHERE s.source ~~ 'runlen-v2-%'::text OR s.source ~~ 'human-v1-%'::text",
     "WHERE derm._is_rule_source(s.source)"),
    ("ORDER BY s.dump_folder, s.effective_page, (s.source ~~ 'human-v1-%'::text) DESC, s.scanned_at DESC",
     "ORDER BY s.dump_folder, s.effective_page, derm._rule_source_rank(s.source), s.scanned_at DESC"),
], 'v_page_printed_rules')

vbec = patch(defs['v_band_edge_check'], [
    ("WHERE page_rule_scans.source ~~ 'runlen-v2-%'::text OR page_rule_scans.source ~~ 'human-v1-%'::text",
     "WHERE derm._is_rule_source(page_rule_scans.source)"),
    ("ORDER BY page_rule_scans.dump_folder, page_rule_scans.effective_page, (page_rule_scans.source ~~ 'human-v1-%'::text) DESC, page_rule_scans.scanned_at DESC",
     "ORDER BY page_rule_scans.dump_folder, page_rule_scans.effective_page, derm._rule_source_rank(page_rule_scans.source), page_rule_scans.scanned_at DESC"),
], 'v_band_edge_check')

rpr = patch(defs['record_page_rules'], [
    ("RAISE EXCEPTION 'source must match runlen-v2-%% or human-v1-%%, got %',",
     "RAISE EXCEPTION 'source must match runlen-v2-%%, human-v1-%% or template-v1-%%, got %',"),
], 'record_page_rules')
if not rpr.rstrip().endswith('$function$'):
    sys.exit('record_page_rules body does not end with $function$')

# the predicate lives in _is_rule_source; assert the live body is the two-prefix one we replace
if "p_source LIKE 'runlen-v2-%' OR p_source LIKE 'human-v1-%'" not in defs['is_rule_source']:
    sys.exit('_is_rule_source is not the two-prefix body this generator expects')

header = '''-- ============================================================================================
-- 2026-09-15_1100_template_rules_precedence.sql   (GENERATED by
-- scripts/probes/generated_finisher/gen_precedence_migration.py from the live bodies; do not edit
-- the view bodies by hand, re-run the generator)
--
-- A third rule source, `template-v1-<date>`: printed lines matched to the layout of a GENERATED sheet
-- by the finisher (derm.fn_generated_page_measured, migration 2026-09-15_1200). Precedence per page:
--     human-v1  (a person marked the lines)            rank 0
--     template-v1 (layout-guided match on a sheet we printed)  rank 1
--     runlen-v2 (the blind detector + classifier)      rank 2
-- A person's lines always win. The layout-guided set outranks the blind classifier's on the same
-- page: when the blind scan graded OK the two are the same six lines anyway, and when it did not
-- (835076 page 2, a half-width boundary) the layout-guided set is the one that is right.
--
-- ONE PREDICATE, ONE RANK, TWO READERS. derm._is_rule_source() already existed (writer side, in
-- record_page_rules); derm._rule_source_rank() is new. Both readers that select a scan are
-- re-pointed at them: derm.v_page_printed_rules AND derm.v_band_edge_check, whose own copy of the
-- selection CTE was missed once already (2026-09-07_1810). record_page_rules' refusal text names
-- the third prefix.
--
-- INERT AT INSTALL: no template-v1 scan exists yet, so both views serve byte-identical rows before
-- and after (VERIFY 1). The precedence is proven on a synthetic scan inside a savepoint (VERIFY 2).
--
-- BODY PROVENANCE: pg_get_viewdef / pg_get_functiondef output patched by anchored replacement, each
-- anchor asserted to occur exactly once by the generator.
-- RULE 8: no table changes, views and functions only.
-- ============================================================================================
BEGIN;

CREATE TEMP TABLE _vppr_before ON COMMIT DROP AS SELECT * FROM derm.v_page_printed_rules;
CREATE TEMP TABLE _vbec_before ON COMMIT DROP AS
  SELECT dump_folder, effective_page, row_id, edge_verdict, slot_verdict FROM derm.v_band_edge_check;

CREATE OR REPLACE FUNCTION derm._rule_source_rank(p_source text)
RETURNS integer
LANGUAGE sql IMMUTABLE
AS $function$
  -- lower wins. NULL for a source no reader admits.
  SELECT CASE
           WHEN p_source LIKE 'human-v1-%'    THEN 0
           WHEN p_source LIKE 'template-v1-%' THEN 1
           WHEN p_source LIKE 'runlen-v2-%'   THEN 2
         END;
$function$;

CREATE OR REPLACE FUNCTION derm._is_rule_source(p_source text)
RETURNS boolean
LANGUAGE sql IMMUTABLE
AS $function$
  SELECT p_source IS NOT NULL
     AND (p_source LIKE 'runlen-v2-%' OR p_source LIKE 'human-v1-%' OR p_source LIKE 'template-v1-%');
$function$;

'''

body = (header
    + 'CREATE OR REPLACE VIEW derm.v_page_printed_rules AS\n' + vppr.rstrip().rstrip(';') + ';\n\n'
    + 'CREATE OR REPLACE VIEW derm.v_band_edge_check AS\n' + vbec.rstrip().rstrip(';') + ';\n\n'
    + rpr.rstrip() + ';\n\n'
    + '''-- --------------------------------------------------------------------------------------------
-- VERIFY
-- --------------------------------------------------------------------------------------------
DO $verify$
DECLARE v_n int; v_url text; v_j jsonb; v_on_before int; v_on_after int;
BEGIN
  -- 1. inert at install: both readers serve the same rows as before
  SELECT count(*) INTO v_n FROM (
    (SELECT * FROM derm.v_page_printed_rules EXCEPT SELECT * FROM _vppr_before)
    UNION ALL
    (SELECT * FROM _vppr_before EXCEPT SELECT * FROM derm.v_page_printed_rules)) d;
  IF v_n <> 0 THEN RAISE EXCEPTION 'VERIFY 1a FAILED: v_page_printed_rules moved % rows', v_n; END IF;
  SELECT count(*) INTO v_n FROM (
    (SELECT dump_folder, effective_page, row_id, edge_verdict, slot_verdict FROM derm.v_band_edge_check EXCEPT SELECT * FROM _vbec_before)
    UNION ALL
    (SELECT * FROM _vbec_before EXCEPT SELECT dump_folder, effective_page, row_id, edge_verdict, slot_verdict FROM derm.v_band_edge_check)) d;
  IF v_n <> 0 THEN RAISE EXCEPTION 'VERIFY 1b FAILED: v_band_edge_check moved % rows', v_n; END IF;

  -- 1c. the rank and the predicate
  IF derm._rule_source_rank('human-v1-x') <> 0 OR derm._rule_source_rank('template-v1-x') <> 1
     OR derm._rule_source_rank('runlen-v2-x') <> 2 OR derm._rule_source_rank('claude-fix') IS NOT NULL
     OR NOT derm._is_rule_source('template-v1-2026-09-15') OR derm._is_rule_source('template-v2-x') OR derm._is_rule_source(NULL) THEN
    RAISE EXCEPTION 'VERIFY 1c FAILED: rank or predicate';
  END IF;

  -- 2. precedence, on a real page inside a savepoint. ticket-310429 p1: one runlen-v2 scan, no human
  --    scan, serving documents (so v_band_edge_check grades it).
  IF EXISTS (SELECT 1 FROM derm.page_rule_scans WHERE dump_folder = 'ticket-310429' AND effective_page = 1 AND source NOT LIKE 'runlen-v2-%') THEN
    RAISE EXCEPTION 'VERIFY 2 SETUP: ticket-310429 p1 is no longer a runlen-only page; pick another fixture';
  END IF;
  SELECT count(*) INTO v_on_before FROM derm.v_band_edge_check WHERE dump_folder = 'ticket-310429' AND effective_page = 1 AND edge_verdict = 'ON_RULE';
  IF v_on_before = 0 THEN RAISE EXCEPTION 'VERIFY 2 SETUP: ticket-310429 p1 has no ON_RULE band to move; pick another fixture'; END IF;
  v_url := (derm.ticket_page_images('310429'))[1];
  BEGIN
    -- a template scan OLDER than the runlen one, with six lines nowhere near the real ones
    INSERT INTO derm.page_rule_scans (dump_folder, effective_page, source_url, n_rules, n_boundaries, grade, source, scanned_at, source_etag)
    VALUES ('ticket-310429', 1, v_url, 6, 6, 'OK', 'template-v1-verify', '2020-01-01', derm._img_etag(v_url));
    INSERT INTO derm.page_row_rules (dump_folder, effective_page, rule_pct, ink_frac, source, run_frac, kind, kind_confirmed)
    SELECT 'ticket-310429', 1, p, 0.9, 'template-v1-verify', 0.99, 'boundary', false FROM unnest(ARRAY[10,20,30,40,50,60]) p;
    IF (SELECT count(*) FROM derm.v_page_printed_rules WHERE dump_folder = 'ticket-310429' AND effective_page = 1 AND source = 'template-v1-verify') <> 6
       OR (SELECT count(*) FROM derm.v_page_printed_rules WHERE dump_folder = 'ticket-310429' AND effective_page = 1 AND source <> 'template-v1-verify') <> 0 THEN
      RAISE EXCEPTION 'VERIFY 2a FAILED: an older template-v1 scan did not outrank the runlen-v2 scan';
    END IF;
    -- the band grader follows: the real bands are now off the (fake) rules, so ON_RULE must drop
    SELECT count(*) INTO v_on_after FROM derm.v_band_edge_check WHERE dump_folder = 'ticket-310429' AND effective_page = 1 AND edge_verdict = 'ON_RULE';
    IF v_on_after >= v_on_before THEN
      RAISE EXCEPTION 'VERIFY 2b FAILED: v_band_edge_check still grades against the runlen scan (ON_RULE % -> %)', v_on_before, v_on_after;
    END IF;
    -- a human scan older still: it wins over the template scan
    INSERT INTO derm.page_rule_scans (dump_folder, effective_page, source_url, n_rules, n_boundaries, grade, source, scanned_at, source_etag)
    VALUES ('ticket-310429', 1, v_url, 7, 7, 'OK', 'human-v1-verify', '2019-01-01', derm._img_etag(v_url));
    INSERT INTO derm.page_row_rules (dump_folder, effective_page, rule_pct, ink_frac, source, run_frac, kind, kind_confirmed)
    SELECT 'ticket-310429', 1, p, 0.9, 'human-v1-verify', 0.99, 'boundary', false FROM unnest(ARRAY[11,21,31,41,51,61,71]) p;
    IF (SELECT count(*) FROM derm.v_page_printed_rules WHERE dump_folder = 'ticket-310429' AND effective_page = 1 AND source = 'human-v1-verify') <> 7 THEN
      RAISE EXCEPTION 'VERIFY 2c FAILED: a human scan did not outrank the template scan';
    END IF;
    -- 2d. record_page_rules accepts the new prefix and refuses an unknown one with the new words
    v_j := derm.record_page_rules('ticket-310429', 1, 'template-v1-verify2', v_url,
             (SELECT jsonb_agg(jsonb_build_object('pct', p, 'run', 0.99, 'kind', 'boundary')) FROM unnest(derm.fn_generated_template_boundaries()) p),
             '{"grade":"OK","detail":"verify"}'::jsonb);
    IF NOT coalesce((v_j->>'wrote')::boolean, false) THEN RAISE EXCEPTION 'VERIFY 2d FAILED: %', v_j; END IF;
    BEGIN
      PERFORM derm.record_page_rules('ticket-310429', 1, 'bogus-v1-x', v_url, '[]'::jsonb, '{}'::jsonb);
      RAISE EXCEPTION 'VERIFY 2e FAILED: an unknown source was accepted';
    EXCEPTION WHEN OTHERS THEN
      IF SQLERRM LIKE 'VERIFY 2e%' THEN RAISE; END IF;
      IF SQLERRM NOT LIKE 'source must match runlen-v2-%, human-v1-% or template-v1-%' THEN
        RAISE EXCEPTION 'VERIFY 2e FAILED: message is "%"', SQLERRM;
      END IF;
    END;
    RAISE EXCEPTION 'RB';   -- roll the fixture back
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'RB' THEN RAISE; END IF;
  END;
  IF EXISTS (SELECT 1 FROM derm.page_rule_scans WHERE source LIKE '%-verify%') THEN
    RAISE EXCEPTION 'VERIFY 2 CLEANUP FAILED: fixture scans survived the rollback';
  END IF;

  RAISE NOTICE 'ALL VERIFY PASSED: inert at install; template-v1 outranks runlen-v2 and is outranked by human-v1 in BOTH readers; record_page_rules admits the prefix.';
END
$verify$;

COMMIT;
''')

out = os.path.join(root, 'docs', 'migrations', '2026-09-15_1100_template_rules_precedence.sql')
with open(out, 'w', encoding='utf-8', newline='\n') as f:
    f.write(body)
print('wrote', out, len(body), 'bytes')
