-- The fields the client Activity shows. __CFG__ = audit.entity_render_config (migration) or pg_temp.activity_cfg (test).
-- None of these tables is one get_record_history accepts (visits, clients, derm_manifests, calendar_tasks), so its output
-- cannot move. clients keeps its six rows exactly; only balance is flagged as a background field.
-- render_type values past render_value's own (text, date, datetime, money, bool, fk) are formatted by fn_activity_value.
INSERT INTO __CFG__ (table_name, column_name, label, render_type, fk_table, fk_label_col, sort_order, is_system) VALUES
  ('properties','address','Address','address',null,null,10,false),
  ('properties','name','Name','text',null,null,20,false),
  ('properties','zone_id','Zone','zone',null,null,30,false),
  ('properties','grease_trap_size_gallons','Grease trap size','gallons',null,null,40,false),
  ('properties','grease_trap_manhole_count','Manholes','text',null,null,50,false),
  ('properties','sample_port_count','Sample ports','text',null,null,60,false),
  ('properties','access_schedule','Access hours','schedule',null,null,70,false),
  ('properties','lock_box_key','Lock box','text',null,null,80,false),
  ('properties','access_notes','Access notes','text',null,null,90,false),
  ('properties','notes','Notes','text',null,null,100,false),
  ('properties','city_emails','City email','list',null,null,110,false),
  ('properties','county','County','text',null,null,120,true),
  ('properties','is_primary','Main site','bool',null,null,130,false),
  ('properties','site_map','Site map','changed',null,null,140,false),
  ('properties','latitude','Map position','pin',null,null,150,true),
  ('properties','geofence_type','Geofence','geofence',null,null,160,true),
  ('properties','deleted_at','Removed','removed',null,null,170,false),
  ('properties','client_id','Client','fk','clients','name',180,false),
  ('jobs','job_status','Status','jobstatus',null,null,10,false),
  ('jobs','title','Title','text',null,null,20,false),
  ('jobs','frequency_days','Frequency','days',null,null,30,false),
  ('jobs','start_at','Start','datetime',null,null,40,false),
  ('jobs','end_at','End','datetime',null,null,50,false),
  ('jobs','billing_type','Billing type','enum',null,null,60,false),
  ('jobs','invoice_frequency','Invoicing','enum',null,null,70,false),
  ('jobs','notes','Instructions','text',null,null,80,false),
  ('jobs','client_id','Client','fk','clients','name',90,false),
  ('line_items','name','Name','text',null,null,10,false),
  ('line_items','description','Description','text',null,null,20,false),
  ('line_items','quantity','Quantity','text',null,null,30,false),
  ('line_items','unit_price','Unit price','money',null,null,40,false),
  ('gdos','gdo_number','GDO number','text',null,null,10,false),
  ('gdos','status','Status','enum',null,null,20,false),
  ('gdos','nickname','Nickname','text',null,null,30,false),
  ('gdos','notes','Notes','text',null,null,40,false),
  ('gdos','location_label','Permit name','text',null,null,50,true),
  ('gdos','permit_expiration','Permit expires','date',null,null,60,false),
  ('gdos','max_frequency_days','Max frequency','days',null,null,70,false),
  ('gdos','permit_document_path','Permit file','changed',null,null,80,false),
  ('gdos','property_id','Site','fk','properties','address',90,false),
  ('gdos','client_location_id','Location','fk','client_locations','name',100,false),
  ('gdos','client_id','Client','fk','clients','name',110,false),
  ('client_contacts','name','Name','text',null,null,10,false),
  ('client_contacts','first_name','First name','text',null,null,20,false),
  ('client_contacts','last_name','Last name','text',null,null,30,false),
  ('client_contacts','email','Email','text',null,null,40,false),
  ('client_contacts','phone','Phone','text',null,null,50,false),
  ('client_contacts','person_role','Role','role',null,null,60,false),
  ('client_contacts','property_id','Site','fk','properties','address',70,false),
  ('client_jobber_contacts','name','Name','text',null,null,10,false),
  ('client_jobber_contacts','first_name','First name','text',null,null,20,false),
  ('client_jobber_contacts','last_name','Last name','text',null,null,30,false),
  ('client_jobber_contacts','email','Email','text',null,null,40,false),
  ('client_jobber_contacts','phone','Phone','text',null,null,50,false),
  ('client_jobber_contacts','person_role','Role','role',null,null,60,false),
  ('client_jobber_contacts','jobber_role','Jobber role','text',null,null,70,false),
  ('client_jobber_contacts','title','Title','text',null,null,80,false),
  ('client_jobber_contacts','is_billing_contact','Billing contact','bool',null,null,90,false),
  ('client_jobber_contacts','deleted_at','Removed','removed',null,null,100,false),
  ('client_locations','name','Name','text',null,null,10,false),
  ('client_locations','status','Status','enum',null,null,20,false),
  ('client_locations','property_id','Site','fk','properties','address',30,false),
  ('client_locations','notes','Notes','text',null,null,40,false),
  ('invoices','invoice_status','Status','enum',null,null,10,false),
  ('invoices','total','Total','money',null,null,20,true),
  ('invoices','outstanding_amount','Balance due','money',null,null,30,true),
  ('invoices','due_date','Due date','date',null,null,40,true),
  ('invoices','deposit_amount','Deposit','money',null,null,50,true);
UPDATE __CFG__ SET is_system = true WHERE table_name = 'clients' AND column_name = 'balance';
